[workspace]
resolver = "3"
members = ["crates/story"]

[workspace.package]
edition = "2024"
license = "MIT"
repository = "https://github.com/eserilev/timeways"

[workspace.dependencies]
rusty-hourglass = { git = "https://github.com/eserilev/rusty-hourglass", rev = "f1a7bb45b3e4c009789c6f7bdc4341ee310b8baf" }

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
pedantic = { level = "warn", priority = -1 }
unwrap_used = "deny"
expect_used = "deny"
