-- The WoW Forever 1.60.1.70009 API that Timeways uses.
-- Written by scripts/wow-api.sh. Do not edit.
return {
	build = "1.60.1.70009",
	globals = {
		"ActionStatus",
		"Ambiguate",
		"C_AddOns",
		"C_AddOns.EnableAddOn",
		"C_AddOns.IsAddOnLoaded",
		"C_AddOns.LoadAddOn",
		"C_CVar",
		"C_ChatInfo",
		"C_ChatInfo.RegisterAddonMessagePrefix",
		"C_ChatInfo.SendAddonMessage",
		"C_ChatInfo.SendAddonMessageLogged",
		"C_Cursor",
		"C_Cursor.GetCursorItem",
		"C_DeathRecap",
		"C_DeathRecap.GetRecapEvents",
		"C_DeathRecap.HasRecapEvents",
		"C_FriendList",
		"C_FriendList.GetFriendInfo",
		"C_FriendList.GetFriendInfoByIndex",
		"C_FriendList.GetNumFriends",
		"C_GossipInfo",
		"C_GossipInfo.GetText",
		"C_GuildInfo",
		"C_GuildInfo.GuildRoster",
		"C_Item",
		"C_Item.GetItemCount",
		"C_Item.GetItemIconByID",
		"C_Item.GetStackCount",
		"C_Map",
		"C_Map.GetBestMapForUnit",
		"C_Map.GetFallbackWorldMapID",
		"C_Map.GetMapArtLayerTextures",
		"C_Map.GetMapArtLayers",
		"C_Map.GetMapChildrenInfo",
		"C_Map.GetMapInfo",
		"C_Map.GetPlayerMapPosition",
		"C_MapExplorationInfo",
		"C_MapExplorationInfo.GetExploredMapTextures",
		"C_QuestLog",
		"C_QuestLog.GetInfo",
		"C_QuestLog.GetNumQuestLogEntries",
		"C_Timer",
		"C_Timer.After",
		"C_Timer.NewTicker",
		"ChatFontNormal",
		"CheckInteractDistance",
		"ClearCursor",
		"CreateFrame",
		"DEFAULT_CHAT_FRAME",
		"Enum",
		"Enum.TooltipDataType.Unit",
		"Enum.UIMapType.Zone",
		"GameTooltip",
		"GetBuildInfo",
		"GetCursorInfo",
		"GetGameMessageInfo",
		"GetGreetingText",
		"GetGuildRosterInfo",
		"GetNormalizedRealmName",
		"GetNumGuildMembers",
		"GetObjectiveText",
		"GetPhysicalScreenSize",
		"GetPlayerTradeMoney",
		"GetProgressText",
		"GetQuestText",
		"GetRealZoneText",
		"GetRealmName",
		"GetRewardText",
		"GetSubZoneText",
		"GetTargetTradeMoney",
		"GetTime",
		"GetTitleText",
		"GetTradePlayerItemInfo",
		"GetTradeTargetItemInfo",
		"InCombatLockdown",
		"IsControlKeyDown",
		"IsInGroup",
		"IsInGuild",
		"IsInInstance",
		"IsInRaid",
		"ItemTextGetCreator",
		"ItemTextGetItem",
		"ItemTextGetText",
		"Menu",
		"PlaySound",
		"ReloadUI",
		"SOUNDKIT",
		"Screenshot",
		"SetCVar",
		"SlashCmdList",
		"StaticPopupDialogs",
		"StaticPopup_Show",
		"TooltipDataProcessor",
		"UIErrorsFrame",
		"UIParent",
		"UISpecialFrames",
		"UnitCanAttack",
		"UnitClass",
		"UnitClassification",
		"UnitCreatureType",
		"UnitExists",
		"UnitFactionGroup",
		"UnitFullName",
		"UnitGUID",
		"UnitIsConnected",
		"UnitIsPlayer",
		"UnitIsSameServer",
		"UnitLevel",
		"UnitName",
		"UnitPlayerControlled",
		"UnitRace",
		"UnitSex",
		"bit",
		"bit.band",
		"bit.bnot",
		"bit.bor",
		"bit.bxor",
		"bit.lshift",
		"bit.rshift",
		"date",
		"hooksecurefunc",
		"issecretvalue",
		"strtrim",
		"time",
	},
	widgets = {
		Alpha = {
			inherits = {
				"Animation",
			},
			methods = {
				"GetFromAlpha",
				"GetToAlpha",
				"SetFromAlpha",
				"SetToAlpha",
			},
		},
		Animation = {
			inherits = {
				"Object",
				"ScriptObject",
			},
			methods = {
				"GetDuration",
				"GetElapsed",
				"GetEndDelay",
				"GetOrder",
				"GetProgress",
				"GetRegionParent",
				"GetSmoothProgress",
				"GetSmoothing",
				"GetStartDelay",
				"GetTarget",
				"IsDelaying",
				"IsDone",
				"IsPaused",
				"IsPlaying",
				"IsStopped",
				"Pause",
				"Play",
				"Restart",
				"SetChildKey",
				"SetDuration",
				"SetEndDelay",
				"SetOrder",
				"SetParent",
				"SetPlaying",
				"SetSmoothProgress",
				"SetSmoothing",
				"SetStartDelay",
				"SetTarget",
				"SetTargetKey",
				"SetTargetName",
				"SetTargetParent",
				"Stop",
			},
		},
		AnimationGroup = {
			inherits = {
				"Object",
				"ScriptObject",
			},
			methods = {
				"CreateAnimation",
				"Finish",
				"GetAnimationSpeedMultiplier",
				"GetAnimations",
				"GetDuration",
				"GetElapsed",
				"GetLoopState",
				"GetLooping",
				"GetProgress",
				"IsDone",
				"IsPaused",
				"IsPendingFinish",
				"IsPlaying",
				"IsReverse",
				"IsSetToFinalAlpha",
				"Pause",
				"Play",
				"RemoveAnimations",
				"Restart",
				"SetAnimationSpeedMultiplier",
				"SetLooping",
				"SetPlaying",
				"SetToFinalAlpha",
				"Stop",
			},
		},
		ArchaeologyDigSiteFrame = {
			inherits = {
				"Blob",
			},
			methods = {
			},
		},
		Blob = {
			inherits = {
				"Frame",
			},
			methods = {
				"DrawAll",
				"DrawBlob",
				"DrawNone",
				"EnableMerging",
				"EnableSmoothing",
				"GetMapID",
				"SetBorderAlpha",
				"SetBorderScalar",
				"SetBorderTexture",
				"SetFillAlpha",
				"SetFillTexture",
				"SetMapID",
				"SetMergeThreshold",
				"SetNumSplinePoints",
			},
		},
		Browser = {
			inherits = {
				"Frame",
			},
			methods = {
				"ClearFocus",
				"CopyExternalLink",
				"DeleteCookies",
				"NavigateBack",
				"NavigateForward",
				"NavigateHome",
				"NavigateReload",
				"NavigateStop",
				"OpenExternalLink",
				"OpenTicket",
				"SetFocus",
				"SetZoom",
			},
		},
		Button = {
			inherits = {
				"Frame",
			},
			methods = {
				"ClearDisabledTexture",
				"ClearHighlightTexture",
				"ClearNormalTexture",
				"ClearPushedTexture",
				"Click",
				"Disable",
				"Enable",
				"GetButtonState",
				"GetDisabledFontObject",
				"GetDisabledTexture",
				"GetFontString",
				"GetHighlightFontObject",
				"GetHighlightTexture",
				"GetMotionScriptsWhileDisabled",
				"GetNormalFontObject",
				"GetNormalTexture",
				"GetPushedTextOffset",
				"GetPushedTexture",
				"GetText",
				"GetTextHeight",
				"GetTextWidth",
				"IsEnabled",
				"RegisterForClicks",
				"RegisterForMouse",
				"SetButtonState",
				"SetDisabledAtlas",
				"SetDisabledFontObject",
				"SetDisabledTexture",
				"SetEnabled",
				"SetFontString",
				"SetFormattedText",
				"SetHighlightAtlas",
				"SetHighlightFontObject",
				"SetHighlightTexture",
				"SetMotionScriptsWhileDisabled",
				"SetNormalAtlas",
				"SetNormalFontObject",
				"SetNormalTexture",
				"SetPushedAtlas",
				"SetPushedTextOffset",
				"SetPushedTexture",
				"SetText",
			},
		},
		CheckButton = {
			inherits = {
				"Button",
			},
			methods = {
				"GetChecked",
				"GetCheckedTexture",
				"GetDisabledCheckedTexture",
				"SetChecked",
				"SetCheckedTexture",
				"SetDisabledCheckedTexture",
			},
		},
		Checkout = {
			inherits = {
				"Frame",
			},
			methods = {
				"CancelOpenCheckout",
				"ClearFocus",
				"CloseCheckout",
				"CopyExternalLink",
				"OpenCheckout",
				"OpenExternalLink",
				"SetFocus",
				"SetZoom",
			},
		},
		CinematicModel = {
			inherits = {
				"PlayerModel",
			},
			methods = {
				"EquipItem",
				"InitializeCamera",
				"InitializePanCamera",
				"SetAnimOffset",
				"SetCreatureData",
				"SetFacingLeft",
				"SetFadeTimes",
				"SetHeightFactor",
				"SetJumpInfo",
				"SetPanDistance",
				"SetSpellVisualKit",
				"SetTargetDistance",
				"StartPan",
				"StopPan",
				"UnequipItems",
			},
		},
		ColorSelect = {
			inherits = {
				"Frame",
			},
			methods = {
				"ClearColorWheelTexture",
				"GetColorAlpha",
				"GetColorAlphaTexture",
				"GetColorAlphaThumbTexture",
				"GetColorHSV",
				"GetColorRGB",
				"GetColorValueTexture",
				"GetColorValueThumbTexture",
				"GetColorWheelTexture",
				"GetColorWheelThumbTexture",
				"SetColorAlpha",
				"SetColorAlphaTexture",
				"SetColorAlphaThumbTexture",
				"SetColorHSV",
				"SetColorRGB",
				"SetColorValueTexture",
				"SetColorValueThumbTexture",
				"SetColorWheelTexture",
				"SetColorWheelThumbTexture",
			},
		},
		ControlPoint = {
			inherits = {
				"Object",
			},
			methods = {
				"GetOffset",
				"GetOrder",
				"SetOffset",
				"SetOrder",
				"SetParent",
			},
		},
		Cooldown = {
			inherits = {
				"Frame",
			},
			methods = {
				"Clear",
				"GetCooldownDisplayDuration",
				"GetCooldownDuration",
				"GetCooldownTimes",
				"GetCountdownAbbrevThreshold",
				"GetCountdownFontString",
				"GetCountdownFormatter",
				"GetCountdownMillisecondsThreshold",
				"GetDrawBling",
				"GetDrawEdge",
				"GetDrawSwipe",
				"GetEdgeScale",
				"GetHideCountdownNumbers",
				"GetMinimumCountdownDuration",
				"GetReverse",
				"GetRotation",
				"GetUseAuraDisplayTime",
				"IsPaused",
				"Pause",
				"Resume",
				"SetBlingTexture",
				"SetCooldown",
				"SetCooldownDuration",
				"SetCooldownFromDurationObject",
				"SetCooldownFromExpirationTime",
				"SetCooldownUNIX",
				"SetCountdownAbbrevThreshold",
				"SetCountdownFont",
				"SetCountdownFormatter",
				"SetCountdownMillisecondsThreshold",
				"SetDrawBling",
				"SetDrawEdge",
				"SetDrawSwipe",
				"SetEdgeColor",
				"SetEdgeScale",
				"SetEdgeTexture",
				"SetHideCountdownNumbers",
				"SetMinimumCountdownDuration",
				"SetPaused",
				"SetReverse",
				"SetRotation",
				"SetSwipeColor",
				"SetSwipeTexture",
				"SetTexCoordRange",
				"SetUseAuraDisplayTime",
				"SetUseCircularEdge",
			},
		},
		DressUpModel = {
			inherits = {
				"PlayerModel",
			},
			methods = {
				"Dress",
				"GetAutoDress",
				"GetItemTransmogInfo",
				"GetItemTransmogInfoList",
				"GetObeyHideInTransmogFlag",
				"GetSheathed",
				"GetUseTransmogChoices",
				"GetUseTransmogSkin",
				"IsGeoReady",
				"IsSlotAllowed",
				"IsSlotVisible",
				"SetAutoDress",
				"SetItemTransmogInfo",
				"SetObeyHideInTransmogFlag",
				"SetSheathed",
				"SetUseTransmogChoices",
				"SetUseTransmogSkin",
				"TryOn",
				"Undress",
				"UndressSlot",
			},
		},
		EditBox = {
			inherits = {
				"FontInstance",
				"Frame",
			},
			methods = {
				"AddHistoryLine",
				"ClearFocus",
				"ClearHighlightText",
				"ClearHistory",
				"Disable",
				"Enable",
				"GetAltArrowKeyMode",
				"GetBlinkSpeed",
				"GetCursorPosition",
				"GetDisplayText",
				"GetHighlightColor",
				"GetHistoryLines",
				"GetInputLanguage",
				"GetMaxBytes",
				"GetMaxLetters",
				"GetNumLetters",
				"GetNumLines",
				"GetNumber",
				"GetText",
				"GetTextInsets",
				"GetUTF8CursorPosition",
				"GetVisibleTextByteLimit",
				"HasFocus",
				"HasText",
				"HighlightText",
				"Insert",
				"IsAlphabeticOnly",
				"IsAutoFocus",
				"IsCountInvisibleLetters",
				"IsEnabled",
				"IsInIMECompositionMode",
				"IsMultiLine",
				"IsNumeric",
				"IsNumericFullRange",
				"IsPassword",
				"IsSecureText",
				"ResetInputMode",
				"SetAlphabeticOnly",
				"SetAltArrowKeyMode",
				"SetAutoFocus",
				"SetBlinkSpeed",
				"SetCountInvisibleLetters",
				"SetCursorPosition",
				"SetEnabled",
				"SetFocus",
				"SetHighlightColor",
				"SetHistoryLines",
				"SetMaxBytes",
				"SetMaxLetters",
				"SetMultiLine",
				"SetNumber",
				"SetNumeric",
				"SetNumericFullRange",
				"SetPassword",
				"SetSecureText",
				"SetSecurityDisablePaste",
				"SetSecurityDisableSetText",
				"SetText",
				"SetTextInsets",
				"SetVisibleTextByteLimit",
				"ToggleInputLanguage",
			},
		},
		FlipBook = {
			inherits = {
				"Animation",
			},
			methods = {
				"GetFlipBookColumns",
				"GetFlipBookFrameHeight",
				"GetFlipBookFrameWidth",
				"GetFlipBookFrames",
				"GetFlipBookRows",
				"SetFlipBookColumns",
				"SetFlipBookFrameHeight",
				"SetFlipBookFrameWidth",
				"SetFlipBookFrames",
				"SetFlipBookRows",
			},
		},
		FogOfWarFrame = {
			inherits = {
				"Frame",
			},
			methods = {
				"GetFogOfWarBackgroundAtlas",
				"GetFogOfWarBackgroundTexture",
				"GetFogOfWarMaskAtlas",
				"GetFogOfWarMaskTexture",
				"GetMaskScalar",
				"GetUiMapID",
				"SetFogOfWarBackgroundAtlas",
				"SetFogOfWarBackgroundTexture",
				"SetFogOfWarMaskAtlas",
				"SetFogOfWarMaskTexture",
				"SetMaskScalar",
				"SetUiMapID",
			},
		},
		Font = {
			inherits = {
				"FontInstance",
				"FrameScriptObject",
			},
			methods = {
				"CopyFontObject",
				"GetAlpha",
				"GetFontHeight",
				"GetFontObjectForAlphabet",
				"SetAlpha",
				"SetFontHeight",
			},
		},
		FontInstance = {
			inherits = {
			},
			methods = {
				"GetFont",
				"GetFontObject",
				"GetIndentedWordWrap",
				"GetJustifyH",
				"GetJustifyV",
				"GetShadowColor",
				"GetShadowOffset",
				"GetSpacing",
				"GetTextColor",
				"SetFont",
				"SetFontObject",
				"SetIndentedWordWrap",
				"SetJustifyH",
				"SetJustifyV",
				"SetShadowColor",
				"SetShadowOffset",
				"SetSpacing",
				"SetTextColor",
			},
		},
		FontString = {
			inherits = {
				"FontInstance",
				"Region",
			},
			methods = {
				"CalculateScreenAreaFromCharacterSpan",
				"CanNonSpaceWrap",
				"CanWordWrap",
				"ClearAlphaGradient",
				"ClearText",
				"FindCharacterIndexAtCoordinate",
				"GetAlphaGradient",
				"GetFieldSize",
				"GetFontHeight",
				"GetLineHeight",
				"GetMaxLines",
				"GetNumLines",
				"GetScaleAnimationMode",
				"GetSmoothScaling",
				"GetStringHeight",
				"GetStringWidth",
				"GetText",
				"GetTextScale",
				"GetUnboundedStringWidth",
				"GetUnboundedStringWidthForText",
				"GetWrappedWidth",
				"IsTruncated",
				"OnColorsUpdated",
				"SetAlphaGradient",
				"SetDesaturateEmbeddedTextures",
				"SetFixedColor",
				"SetFontHeight",
				"SetFormattedText",
				"SetMaxLines",
				"SetNonSpaceWrap",
				"SetScaleAnimationMode",
				"SetSmoothScaling",
				"SetText",
				"SetTextHeight",
				"SetTextScale",
				"SetTextToFit",
				"SetWordWrap",
			},
		},
		Frame = {
			inherits = {
				"ScriptRegion",
			},
			methods = {
				"AbortDrag",
				"AddRoleset",
				"CanChangeAttribute",
				"ClearAlphaGradient",
				"ClearAttribute",
				"ClearAttributes",
				"CreateFontString",
				"CreateLine",
				"CreateMaskTexture",
				"CreateTexture",
				"CreateVectorGraphics",
				"DesaturateHierarchy",
				"DisableDrawLayer",
				"DoesClipChildren",
				"DoesHyperlinkPropagateToParent",
				"EnableDrawLayer",
				"EnableGamePadButton",
				"EnableGamePadStick",
				"EnableKeyboard",
				"ExecuteAttribute",
				"GetAttribute",
				"GetBoundsRect",
				"GetChildren",
				"GetClampRectInsets",
				"GetDontSavePosition",
				"GetEffectiveAlpha",
				"GetEffectivelyFlattensRenderLayers",
				"GetFlattensRenderLayers",
				"GetFrameLevel",
				"GetFrameStrata",
				"GetHighestFrameLevel",
				"GetHitRectInsets",
				"GetHyperlinksEnabled",
				"GetID",
				"GetNumChildren",
				"GetNumRegions",
				"GetOnUpdateMode",
				"GetPropagateKeyboardInput",
				"GetRaisedFrameLevel",
				"GetRegions",
				"GetResizeBounds",
				"GetRolesetNames",
				"GetWindow",
				"HasAlphaGradient",
				"HasFixedFrameLevel",
				"HasFixedFrameStrata",
				"InterceptStartDrag",
				"IsClampedToScreen",
				"IsDrawLayerEnabled",
				"IsEventRegistered",
				"IsFrameBuffer",
				"IsGamePadButtonEnabled",
				"IsGamePadStickEnabled",
				"IsHighlightLocked",
				"IsIgnoringChildrenForBounds",
				"IsKeyboardEnabled",
				"IsMovable",
				"IsResizable",
				"IsRolesetFiltered",
				"IsToplevel",
				"IsUserPlaced",
				"IsUsingParentLevel",
				"LockHighlight",
				"Lower",
				"Raise",
				"RegisterAllEvents",
				"RegisterEvent",
				"RegisterEventCallback",
				"RegisterForDrag",
				"RegisterUnitEvent",
				"RegisterUnitEventCallback",
				"RemoveRoleset",
				"ResizeToBoundsRect",
				"RotateTextures",
				"SetAlphaGradient",
				"SetAttribute",
				"SetAttributeNoHandler",
				"SetClampRectInsets",
				"SetClampedToScreen",
				"SetClipsChildren",
				"SetDontSavePosition",
				"SetDrawLayerEnabled",
				"SetFixedFrameLevel",
				"SetFixedFrameStrata",
				"SetFlattensRenderLayers",
				"SetFrameLevel",
				"SetFrameStrata",
				"SetHighlightLocked",
				"SetHitRectInsets",
				"SetHyperlinkPropagateToParent",
				"SetHyperlinksEnabled",
				"SetID",
				"SetIgnoringChildrenForBounds",
				"SetIsFrameBuffer",
				"SetMovable",
				"SetOnUpdateMode",
				"SetPropagateKeyboardInput",
				"SetResizable",
				"SetResizeBounds",
				"SetRolesets",
				"SetToplevel",
				"SetUserPlaced",
				"SetUsingParentLevel",
				"SetWindow",
				"StartMoving",
				"StartSizing",
				"StopMovingOrSizing",
				"UnlockHighlight",
				"UnregisterAllEvents",
				"UnregisterEvent",
			},
		},
		FrameScriptObject = {
			inherits = {
			},
			methods = {
				"AddAccessRestrictions",
				"AddForbiddenAspects",
				"AddSecretAspect",
				"CanBeAccessedInContext",
				"GetAccessRestrictions",
				"GetForbiddenAspects",
				"GetInheritableForbiddenAspects",
				"GetName",
				"GetObjectTable",
				"GetObjectType",
				"HasAccessConstraints",
				"HasAnyAccessRestrictions",
				"HasAnyForbiddenAspects",
				"HasAnySecretAspect",
				"HasSecretAspect",
				"HasSecretValues",
				"IsForbidden",
				"IsObjectType",
				"IsPreventingSecretValues",
				"SetForbidden",
				"SetToDefaults",
			},
		},
		GameTooltip = {
			inherits = {
				"Frame",
			},
			methods = {
				"AddAtlas",
				"AddDoubleLine",
				"AddFontStrings",
				"AddLine",
				"AddTexture",
				"AppendText",
				"ClearLines",
				"ClearPadding",
				"CopyTooltip",
				"FadeOut",
				"GetAnchorType",
				"GetCustomLineSpacing",
				"GetLeftLine",
				"GetMinimumWidth",
				"GetOwner",
				"GetPadding",
				"GetRightLine",
				"IsOwned",
				"NumLines",
				"SetAllowShowWithNoLines",
				"SetAnchorType",
				"SetCustomLineSpacing",
				"SetCustomWordWrapMinWidth",
				"SetFrameStack",
				"SetMinimumWidth",
				"SetObjectTooltipPosition",
				"SetOwner",
				"SetPadding",
				"SetShrinkToFitWrapped",
				"SetText",
			},
		},
		Line = {
			inherits = {
				"TextureBase",
			},
			methods = {
				"GetEndPoint",
				"GetHitRectThickness",
				"GetStartPoint",
				"GetThickness",
				"SetEndPoint",
				"SetHitRectThickness",
				"SetStartPoint",
				"SetThickness",
			},
		},
		LineScale = {
			inherits = {
				"Animation",
			},
			methods = {
				"GetOrigin",
				"GetScale",
				"GetScaleFrom",
				"GetScaleTo",
				"SetOrigin",
				"SetScale",
				"SetScaleFrom",
				"SetScaleTo",
			},
		},
		LineTranslation = {
			inherits = {
				"Animation",
			},
			methods = {
				"GetOffset",
				"SetOffset",
			},
		},
		MaskTexture = {
			inherits = {
				"TextureBase",
			},
			methods = {
			},
		},
		MessageFrame = {
			inherits = {
				"FontInstance",
				"Frame",
			},
			methods = {
				"AddMessage",
				"Clear",
				"GetFadeDuration",
				"GetFadePower",
				"GetFading",
				"GetFontStringByID",
				"GetInsertMode",
				"GetTimeVisible",
				"HasMessageByID",
				"ResetMessageFadeByID",
				"SetFadeDuration",
				"SetFadePower",
				"SetFading",
				"SetInsertMode",
				"SetTimeVisible",
			},
		},
		Minimap = {
			inherits = {
				"Frame",
			},
			methods = {
				"GetPingPosition",
				"GetZoom",
				"GetZoomLevels",
				"PingLocation",
				"SetArchBlobInsideAlpha",
				"SetArchBlobInsideTexture",
				"SetArchBlobOutsideAlpha",
				"SetArchBlobOutsideTexture",
				"SetArchBlobRingAlpha",
				"SetArchBlobRingScalar",
				"SetArchBlobRingTexture",
				"SetIconScale",
				"SetMaskTexture",
				"SetQuestBlobInsideAlpha",
				"SetQuestBlobInsideTexture",
				"SetQuestBlobOutsideAlpha",
				"SetQuestBlobOutsideTexture",
				"SetQuestBlobRingAlpha",
				"SetQuestBlobRingScalar",
				"SetQuestBlobRingTexture",
				"SetTaskBlobInsideAlpha",
				"SetTaskBlobInsideTexture",
				"SetTaskBlobOutsideAlpha",
				"SetTaskBlobOutsideTexture",
				"SetTaskBlobRingAlpha",
				"SetTaskBlobRingScalar",
				"SetTaskBlobRingTexture",
				"SetUsingSoftCursor",
				"SetZoom",
				"UpdateBlips",
				"UpdateMouseoverAtPoint",
			},
		},
		Model = {
			inherits = {
				"Frame",
			},
			methods = {
				"AdvanceTime",
				"ClearFog",
				"ClearModel",
				"ClearTransform",
				"GetCameraDistance",
				"GetCameraFacing",
				"GetCameraPosition",
				"GetCameraRoll",
				"GetCameraTarget",
				"GetDesaturation",
				"GetFacing",
				"GetFogColor",
				"GetFogFar",
				"GetFogNear",
				"GetLight",
				"GetModelAlpha",
				"GetModelDrawLayer",
				"GetModelFileID",
				"GetModelScale",
				"GetPaused",
				"GetPitch",
				"GetPosition",
				"GetRoll",
				"GetShadowEffect",
				"GetViewInsets",
				"GetViewTranslation",
				"GetWorldScale",
				"HasAttachmentPoints",
				"HasCustomCamera",
				"IsUsingModelCenterToTransform",
				"MakeCurrentCameraCustom",
				"ReplaceIconTexture",
				"SetCamera",
				"SetCameraDistance",
				"SetCameraFacing",
				"SetCameraPosition",
				"SetCameraRoll",
				"SetCameraTarget",
				"SetCustomCamera",
				"SetDesaturation",
				"SetFacing",
				"SetFogColor",
				"SetFogFar",
				"SetFogNear",
				"SetGlow",
				"SetGradientMask",
				"SetLight",
				"SetModel",
				"SetModelAlpha",
				"SetModelDrawLayer",
				"SetModelScale",
				"SetParticlesEnabled",
				"SetPaused",
				"SetPitch",
				"SetPosition",
				"SetRoll",
				"SetSequence",
				"SetSequenceTime",
				"SetShadowEffect",
				"SetTransform",
				"SetUseGBuffer",
				"SetViewInsets",
				"SetViewTranslation",
				"TransformCameraSpaceToModelSpace",
				"UseModelCenterToTransform",
			},
		},
		ModelScene = {
			inherits = {
				"Frame",
			},
			methods = {
				"ClearFog",
				"CreateActor",
				"GetActorAtIndex",
				"GetAllowOverlappedModels",
				"GetCameraFarClip",
				"GetCameraFieldOfView",
				"GetCameraForward",
				"GetCameraNearClip",
				"GetCameraPosition",
				"GetCameraRight",
				"GetCameraUp",
				"GetDrawLayer",
				"GetFogColor",
				"GetFogFar",
				"GetFogNear",
				"GetLightAmbientColor",
				"GetLightDiffuseColor",
				"GetLightDirection",
				"GetLightPosition",
				"GetLightType",
				"GetNumActors",
				"GetViewInsets",
				"GetViewTranslation",
				"IsLightVisible",
				"Project3DPointTo2D",
				"SetAllowOverlappedModels",
				"SetCameraFarClip",
				"SetCameraFieldOfView",
				"SetCameraNearClip",
				"SetCameraOrientationByAxisVectors",
				"SetCameraOrientationByYawPitchRoll",
				"SetCameraPosition",
				"SetDesaturation",
				"SetDrawLayer",
				"SetFogColor",
				"SetFogFar",
				"SetFogNear",
				"SetLightAmbientColor",
				"SetLightDiffuseColor",
				"SetLightDirection",
				"SetLightPosition",
				"SetLightType",
				"SetLightVisible",
				"SetPaused",
				"SetViewInsets",
				"SetViewTranslation",
				"TakeActor",
			},
		},
		ModelSceneActor = {
			inherits = {
				"Object",
			},
			methods = {
				"AttachToMount",
				"CalculateMountScale",
				"ClearModel",
				"DetachFromMount",
				"Dress",
				"DressPlayerSlot",
				"GetActiveBoundingBox",
				"GetAlpha",
				"GetAnimation",
				"GetAnimationBlendOperation",
				"GetAnimationVariation",
				"GetAutoDress",
				"GetDesaturation",
				"GetItemTransmogInfo",
				"GetItemTransmogInfoList",
				"GetMaxBoundingBox",
				"GetModelFileID",
				"GetModelPath",
				"GetModelUnitGUID",
				"GetObeyHideInTransmogFlag",
				"GetParticleOverrideScale",
				"GetPaused",
				"GetPitch",
				"GetPosition",
				"GetRoll",
				"GetScale",
				"GetSheathed",
				"GetSpellVisualKit",
				"GetUseTransmogChoices",
				"GetUseTransmogSkin",
				"GetYaw",
				"Hide",
				"IsGeoReady",
				"IsLoaded",
				"IsPreferringModelCollisionBounds",
				"IsShown",
				"IsSlotAllowed",
				"IsSlotVisible",
				"IsUsingCenterForOrigin",
				"IsVisible",
				"PlayAnimationKit",
				"ReleaseFrontEndCharacterDisplays",
				"ResetNextHandSlot",
				"SetAlpha",
				"SetAnimation",
				"SetAnimationBlendOperation",
				"SetAutoDress",
				"SetDesaturation",
				"SetFrontEndLobbyModelFromDefaultCharacterDisplay",
				"SetGradientMask",
				"SetGradientMaskWithDyes",
				"SetItemTransmogInfo",
				"SetModelByCreatureDisplayID",
				"SetModelByFileID",
				"SetModelByHyperlink",
				"SetModelByPath",
				"SetModelByUnit",
				"SetModelByUnitCreatureDisplayID",
				"SetObeyHideInTransmogFlag",
				"SetParticleOverrideScale",
				"SetPaused",
				"SetPitch",
				"SetPlayerModelFromGlues",
				"SetPosition",
				"SetPreferModelCollisionBounds",
				"SetRoll",
				"SetScale",
				"SetSheathed",
				"SetSheathedCategory",
				"SetShown",
				"SetSpellVisualKit",
				"SetUseCenterForOrigin",
				"SetUseTransmogChoices",
				"SetUseTransmogSkin",
				"SetYaw",
				"Show",
				"StopAnimationKit",
				"TryOn",
				"Undress",
				"UndressSlot",
				"UseUnitSheatheCategory",
			},
		},
		MovieFrame = {
			inherits = {
				"Frame",
			},
			methods = {
				"EnableSubtitles",
				"StartMovie",
				"StartMovieByName",
				"StopMovie",
			},
		},
		Object = {
			inherits = {
				"FrameScriptObject",
			},
			methods = {
				"ClearParentKey",
				"GetDebugName",
				"GetParent",
				"GetParentKey",
				"IsObjectType",
				"SetParentKey",
			},
		},
		OffScreenFrame = {
			inherits = {
				"Frame",
			},
			methods = {
				"ApplySnapshot",
				"Flush",
				"GetMaxSnapshots",
				"IsSnapshotValid",
				"SetMaxSnapshots",
				"TakeSnapshot",
				"TestPrintToFile",
				"UsesNPOT",
			},
		},
		Path = {
			inherits = {
				"Animation",
			},
			methods = {
				"CreateControlPoint",
				"GetControlPoints",
				"GetCurveType",
				"GetMaxControlPointOrder",
				"SetCurveType",
			},
		},
		PlayerModel = {
			inherits = {
				"Model",
			},
			methods = {
				"ApplySpellVisualKit",
				"CanSetUnit",
				"FreezeAnimation",
				"GetDisplayInfo",
				"GetDoBlend",
				"GetKeepModelOnHide",
				"HasAnimation",
				"PlayAnimKit",
				"RefreshCamera",
				"RefreshUnit",
				"SetAnimation",
				"SetBarberShopAlternateForm",
				"SetCamDistanceScale",
				"SetCreature",
				"SetDisplayInfo",
				"SetDoBlend",
				"SetItem",
				"SetItemAppearance",
				"SetKeepModelOnHide",
				"SetPortraitZoom",
				"SetRotation",
				"SetUnit",
				"StopAnimKit",
				"ZeroCachedCenterXY",
			},
		},
		QuestPOIFrame = {
			inherits = {
				"Blob",
			},
			methods = {
				"GetNumTooltips",
				"GetTooltipIndex",
				"UpdateMouseOverTooltip",
			},
		},
		RadialProgress = {
			inherits = {
				"Animation",
			},
			methods = {
				"GetFromPercent",
				"GetToPercent",
				"SetFromPercent",
				"SetToPercent",
			},
		},
		Region = {
			inherits = {
				"ScriptRegion",
			},
			methods = {
				"GetDrawLayer",
				"GetRotation",
				"GetVertexColor",
				"SetDrawLayer",
				"SetRotation",
				"SetVertexColor",
				"SetVertexColorFromBoolean",
			},
		},
		Rotation = {
			inherits = {
				"Animation",
			},
			methods = {
				"GetDegrees",
				"GetOrigin",
				"GetRadians",
				"SetDegrees",
				"SetOrigin",
				"SetRadians",
			},
		},
		Scale = {
			inherits = {
				"Animation",
			},
			methods = {
				"GetOrigin",
				"GetScale",
				"GetScaleFrom",
				"GetScaleTo",
				"SetOrigin",
				"SetScale",
				"SetScaleFrom",
				"SetScaleTo",
			},
		},
		ScenarioPOIFrame = {
			inherits = {
				"Blob",
			},
			methods = {
				"GetScenarioTooltipText",
				"UpdateMouseOverTooltip",
			},
		},
		ScriptObject = {
			inherits = {
			},
			methods = {
				"GetScript",
				"HasScript",
				"HookScript",
				"SetScript",
			},
		},
		ScriptRegion = {
			inherits = {
				"Object",
				"ScriptObject",
			},
			methods = {
				"AdjustPointsOffset",
				"CanChangeProtectedState",
				"CanPropagateMouseClicks",
				"CanPropagateMouseMotion",
				"ClearAllPoints",
				"ClearPoint",
				"ClearPointsOffset",
				"ClearScripts",
				"CollapsesLayout",
				"CreateAnimationGroup",
				"EnableMouse",
				"EnableMouseMotion",
				"EnableMouseWheel",
				"FocusEnter",
				"FocusExit",
				"GetAlpha",
				"GetAnimationGroups",
				"GetBottom",
				"GetCenter",
				"GetEffectiveScale",
				"GetHeight",
				"GetLeft",
				"GetNumPoints",
				"GetPoint",
				"GetPointByName",
				"GetRect",
				"GetRight",
				"GetRoundLayoutToNearestPixel",
				"GetScale",
				"GetScaledRect",
				"GetSize",
				"GetSourceLocation",
				"GetTop",
				"GetWidth",
				"Hide",
				"Intersects",
				"IsAnchoringRestricted",
				"IsAnchoringSecret",
				"IsCollapsed",
				"IsDragging",
				"IsIgnoringParentAlpha",
				"IsIgnoringParentScale",
				"IsMouseClickEnabled",
				"IsMouseEnabled",
				"IsMouseMotionEnabled",
				"IsMouseMotionFocus",
				"IsMouseOver",
				"IsMouseWheelEnabled",
				"IsObjectLoaded",
				"IsProtected",
				"IsRectValid",
				"IsShown",
				"IsVisible",
				"MouseDown",
				"MouseUp",
				"SetAllPoints",
				"SetAlpha",
				"SetAlphaFromBoolean",
				"SetCollapsesLayout",
				"SetHeight",
				"SetIgnoreParentAlpha",
				"SetIgnoreParentScale",
				"SetMouseClickEnabled",
				"SetMouseMotionEnabled",
				"SetParent",
				"SetPassThroughButtons",
				"SetPoint",
				"SetPointsOffset",
				"SetPropagateMouseClicks",
				"SetPropagateMouseMotion",
				"SetRoundLayoutToNearestPixel",
				"SetScale",
				"SetShown",
				"SetSize",
				"SetWidth",
				"ShouldButtonPassThrough",
				"Show",
				"StopAnimating",
			},
		},
		ScrollFrame = {
			inherits = {
				"Frame",
			},
			methods = {
				"GetHorizontalScroll",
				"GetHorizontalScrollRange",
				"GetScrollChild",
				"GetVerticalScroll",
				"GetVerticalScrollRange",
				"SetHorizontalScroll",
				"SetScrollChild",
				"SetVerticalScroll",
				"UpdateScrollChildRect",
			},
		},
		SimpleHTML = {
			inherits = {
				"FontInstance",
				"Frame",
			},
			methods = {
				"GetContentHeight",
				"GetHyperlinkFormat",
				"GetTextData",
				"SetHyperlinkFormat",
				"SetText",
			},
		},
		Slider = {
			inherits = {
				"Frame",
			},
			methods = {
				"Disable",
				"Enable",
				"GetMinMaxValues",
				"GetObeyStepOnDrag",
				"GetOrientation",
				"GetStepsPerPage",
				"GetThumbTexture",
				"GetValue",
				"GetValueStep",
				"IsDraggingThumb",
				"IsEnabled",
				"SetEnabled",
				"SetMinMaxValues",
				"SetObeyStepOnDrag",
				"SetOrientation",
				"SetStepsPerPage",
				"SetThumbTexture",
				"SetValue",
				"SetValueStep",
			},
		},
		StatusBar = {
			inherits = {
				"Frame",
			},
			methods = {
				"GetFillStyle",
				"GetInterpolatedValue",
				"GetMinMaxValues",
				"GetOrientation",
				"GetRenderMode",
				"GetReverseFill",
				"GetRotatesTexture",
				"GetStatusBarColor",
				"GetStatusBarDesaturation",
				"GetStatusBarTexture",
				"GetTimerDuration",
				"GetValue",
				"IsInterpolating",
				"IsStatusBarDesaturated",
				"SetColorFill",
				"SetFillStyle",
				"SetMinMaxValues",
				"SetOrientation",
				"SetRenderMode",
				"SetReverseFill",
				"SetRotatesTexture",
				"SetStatusBarColor",
				"SetStatusBarDesaturated",
				"SetStatusBarDesaturation",
				"SetStatusBarTexture",
				"SetTimerDuration",
				"SetToTargetValue",
				"SetValue",
			},
		},
		TabardModel = {
			inherits = {
				"PlayerModel",
			},
			methods = {
				"CanSaveTabardNow",
				"CycleVariation",
				"GetLowerBackgroundFileName",
				"GetLowerBorderFile",
				"GetLowerEmblemFile",
				"GetLowerEmblemTexture",
				"GetUpperBackgroundFileName",
				"GetUpperBorderFile",
				"GetUpperEmblemFile",
				"GetUpperEmblemTexture",
				"InitializeTabardColors",
				"IsGuildTabard",
				"Save",
			},
		},
		Texture = {
			inherits = {
				"TextureBase",
			},
			methods = {
				"AddMaskTexture",
				"GetMaskTexture",
				"GetNumMaskTextures",
				"RemoveMaskTexture",
			},
		},
		TextureBase = {
			inherits = {
				"Region",
			},
			methods = {
				"ClearRadialProgressBar",
				"ClearSVG",
				"ClearTextureSlice",
				"ClearVertexOffsets",
				"GetAtlas",
				"GetBlendMode",
				"GetDesaturation",
				"GetHorizTile",
				"GetRadialProgressBarEndOffset",
				"GetRadialProgressBarFeather",
				"GetRadialProgressBarPercent",
				"GetRadialProgressBarReverse",
				"GetRadialProgressBarStartOffset",
				"GetTexCoord",
				"GetTexelSnappingBias",
				"GetTexture",
				"GetTextureFileID",
				"GetTextureFilePath",
				"GetTextureSliceMargins",
				"GetTextureSliceMode",
				"GetVertTile",
				"GetVertexOffset",
				"IsBlockingLoadRequested",
				"IsDesaturated",
				"IsSnappingToPixelGrid",
				"ResetTexCoord",
				"SetAtlas",
				"SetBlendMode",
				"SetBlockingLoadsRequested",
				"SetColorTexture",
				"SetDesaturated",
				"SetDesaturation",
				"SetGradient",
				"SetHorizTile",
				"SetMask",
				"SetRadialProgressBarEndOffset",
				"SetRadialProgressBarFeather",
				"SetRadialProgressBarPercent",
				"SetRadialProgressBarReverse",
				"SetRadialProgressBarStartOffset",
				"SetSVG",
				"SetSnapToPixelGrid",
				"SetSpriteSheetCell",
				"SetTexCoord",
				"SetTexelSnappingBias",
				"SetTexture",
				"SetTextureSliceMargins",
				"SetTextureSliceMode",
				"SetVertTile",
				"SetVertexOffset",
			},
		},
		TextureCoordTranslation = {
			inherits = {
				"Animation",
			},
			methods = {
				"GetOffset",
				"SetOffset",
			},
		},
		Translation = {
			inherits = {
				"Animation",
			},
			methods = {
				"GetOffset",
				"SetOffset",
			},
		},
		UnitPositionFrame = {
			inherits = {
				"Frame",
			},
			methods = {
				"AddUnit",
				"ClearUnits",
				"FinalizeUnits",
				"GetMouseOverUnits",
				"GetPlayerPingScale",
				"GetUiMapID",
				"SetPlayerPingScale",
				"SetPlayerPingTexture",
				"SetUiMapID",
				"SetUnitColor",
				"StartPlayerPing",
				"StopPlayerPing",
			},
		},
		VectorGraphics = {
			inherits = {
				"Region",
			},
			methods = {
				"ClearSVG",
				"GetSVGFileID",
				"HasSVG",
				"SetSVG",
			},
		},
		VertexColor = {
			inherits = {
				"Animation",
			},
			methods = {
				"GetEndColor",
				"GetStartColor",
				"SetEndColor",
				"SetStartColor",
			},
		},
	},
	templates = {
		BackdropTemplate = {
			base = "Frame",
			names = {
				"ApplyBackdrop",
				"ClearBackdrop",
				"GetBackdrop",
				"GetBackdropBorderColor",
				"GetBackdropColor",
				"GetEdgeSize",
				"HasBackdropInfo",
				"OnBackdropLoaded",
				"OnBackdropSizeChanged",
				"SetBackdrop",
				"SetBackdropBorderColor",
				"SetBackdropColor",
				"SetBorderBlendMode",
				"SetupPieceVisuals",
				"SetupTextureCoordinates",
			},
		},
		InputBoxTemplate = {
			base = "EditBox",
			names = {
				"Left",
				"Middle",
				"NarrationGetContext",
				"NarrationGetDescription",
				"NarrationGetName",
				"Right",
				"SetNarrationLabelRegion",
			},
		},
		UIPanelButtonTemplate = {
			base = "Button",
			names = {
				"FitToText",
				"GetDisabledTooltip",
				"Left",
				"Middle",
				"OnEnter",
				"OnLeave",
				"Right",
				"SetDisabledState",
				"SetDisabledTooltip",
				"SetTextToFit",
				"Text",
			},
		},
		UIPanelScrollFrameTemplate = {
			base = "ScrollFrame",
			names = {
				"ScrollBar",
			},
		},
	},
}
