-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [timeways_rules]: function definitions
module
public import Aeneas
public import Timeways.Types
public import Timeways.FunsExternal
@[expose] public section
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace timeways_rules

/-- Trait implementation: [core::option::{impl core::clone::Clone for core::option::Option<T>}]
    Source: '/rustc/library/core/src/option.rs', lines 2271:0-2275:40
    Name pattern: [core::clone::Clone<core::option::Option<@T>>] -/
@[reducible, rust_trait_impl "core::clone::Clone<core::option::Option<@T>>"]
def core.option.Option.Insts.CoreCloneClone {T : Type} (cloneCloneInst :
  core.clone.Clone T) : core.clone.Clone (Option T) := {
  clone := core.option.Option.Insts.CoreCloneClone.clone cloneCloneInst
}

/-- [timeways_rules::aliases::{impl core::clone::Clone for timeways_rules::aliases::PlayerId}::clone]:
    Source: 'crates/rules/src/aliases.rs', lines 9:9-9:14
    Visibility: public -/
def aliases.PlayerId.Insts.CoreCloneClone.clone
  (self : aliases.PlayerId) : Result aliases.PlayerId := do
  ok self

/-- [timeways_rules::aliases::{impl core::clone::Clone for timeways_rules::aliases::Alias}::clone]:
    Source: 'crates/rules/src/aliases.rs', lines 13:9-13:14
    Visibility: public -/
def aliases.Alias.Insts.CoreCloneClone.clone
  (self : aliases.Alias) : Result aliases.Alias := do
  let s ← alloc.string.String.Insts.CoreCloneClone.clone self.key
  let s1 ← alloc.string.String.Insts.CoreCloneClone.clone self.shown
  ok { key := s, shown := s1 }

/-- [timeways_rules::aliases::{impl core::clone::Clone for timeways_rules::aliases::Piece}::clone]:
    Source: 'crates/rules/src/aliases.rs', lines 22:9-22:14
    Visibility: public -/
def aliases.Piece.Insts.CoreCloneClone.clone
  (self : aliases.Piece) : Result aliases.Piece := do
  match self with
  | aliases.Piece.Text __self_0 =>
    let s ← alloc.string.String.Insts.CoreCloneClone.clone __self_0
    ok (aliases.Piece.Text s)
  | aliases.Piece.Word __self_0 __self_1 =>
    let s ← alloc.string.String.Insts.CoreCloneClone.clone __self_0
    let s1 ← alloc.string.String.Insts.CoreCloneClone.clone __self_1
    ok (aliases.Piece.Word s s1)
  | aliases.Piece.Player __self_0 =>
    let pi ← aliases.PlayerId.Insts.CoreCloneClone.clone __self_0
    ok (aliases.Piece.Player pi)

/-- [timeways_rules::aliases::find]: loop 0:
    Source: 'crates/rules/src/aliases.rs', lines 44:4-51:1
    Visibility: public -/
@[rust_loop]
def aliases.find_loop
  (table : Slice aliases.Alias) (key : String) (place : Std.Usize) :
  Result (Option aliases.PlayerId)
  := do
  let i := Slice.len table
  if place < i
  then
    let a ← Slice.index_usize table place
    let b ← alloc.string.String.Insts.CoreCmpPartialEqString.eq a.key key
    if b
    then ok (some place)
    else let place1 ← place + 1#usize
         aliases.find_loop table key place1
  else ok none
partial_fixpoint

/-- [timeways_rules::aliases::find]:
    Source: 'crates/rules/src/aliases.rs', lines 42:0-51:1
    Visibility: public -/
@[reducible]
def aliases.find
  (table : Slice aliases.Alias) (key : String) :
  Result (Option aliases.PlayerId)
  := do
  aliases.find_loop table key 0#usize

/-- [timeways_rules::aliases::learn]:
    Source: 'crates/rules/src/aliases.rs', lines 55:0-62:1
    Visibility: public -/
def aliases.learn
  (table : alloc.vec.Vec aliases.Alias) («alias» : aliases.Alias) :
  Result (aliases.PlayerId × (alloc.vec.Vec aliases.Alias))
  := do
  let s := alloc.vec.Vec.deref table
  let o ← aliases.find s «alias».key
  match o with
  | none =>
    let i := alloc.vec.Vec.len table
    let table1 ← alloc.vec.Vec.push table «alias»
    ok (i, table1)
  | some id => ok (id, table)

/-- [timeways_rules::aliases::learn_all]: loop 0:
    Source: 'crates/rules/src/aliases.rs', lines 68:4-71:5
    Visibility: public -/
@[rust_loop]
def aliases.learn_all_loop
  (table : alloc.vec.Vec aliases.Alias) (names : Slice aliases.Alias)
  (index : Std.Usize) :
  Result (alloc.vec.Vec aliases.Alias)
  := do
  let i := Slice.len names
  if index < i
  then
    let a ← Slice.index_usize names index
    let a1 ← aliases.Alias.Insts.CoreCloneClone.clone a
    let (_, table1) ← aliases.learn table a1
    let index1 ← index + 1#usize
    aliases.learn_all_loop table1 names index1
  else ok table
partial_fixpoint

/-- [timeways_rules::aliases::learn_all]:
    Source: 'crates/rules/src/aliases.rs', lines 66:0-72:1
    Visibility: public -/
@[reducible]
def aliases.learn_all
  (table : alloc.vec.Vec aliases.Alias) (names : Slice aliases.Alias) :
  Result (alloc.vec.Vec aliases.Alias)
  := do
  aliases.learn_all_loop table names 0#usize

/-- [timeways_rules::aliases::to_id]:
    Source: 'crates/rules/src/aliases.rs', lines 75:0-82:1 -/
def aliases.to_id
  (table : Slice aliases.Alias) (piece : aliases.Piece) :
  Result aliases.Piece
  := do
  match piece with
  | aliases.Piece.Text _ => aliases.Piece.Insts.CoreCloneClone.clone piece
  | aliases.Piece.Word key _ =>
    let o ← aliases.find table key
    match o with
    | none => aliases.Piece.Insts.CoreCloneClone.clone piece
    | some id => ok (aliases.Piece.Player id)
  | aliases.Piece.Player _ => aliases.Piece.Insts.CoreCloneClone.clone piece

/-- [timeways_rules::aliases::to_ids]: loop 0:
    Source: 'crates/rules/src/aliases.rs', lines 90:4-93:5
    Visibility: public -/
@[rust_loop]
def aliases.to_ids_loop
  (table : Slice aliases.Alias) (pieces : Slice aliases.Piece)
  (swapped : alloc.vec.Vec aliases.Piece) (index : Std.Usize) :
  Result (alloc.vec.Vec aliases.Piece)
  := do
  let i := Slice.len pieces
  if index < i
  then
    let p ← Slice.index_usize pieces index
    let p1 ← aliases.to_id table p
    let swapped1 ← alloc.vec.Vec.push swapped p1
    let index1 ← index + 1#usize
    aliases.to_ids_loop table pieces swapped1 index1
  else ok swapped
partial_fixpoint

/-- [timeways_rules::aliases::to_ids]:
    Source: 'crates/rules/src/aliases.rs', lines 87:0-95:1
    Visibility: public -/
@[reducible]
def aliases.to_ids
  (table : Slice aliases.Alias) (pieces : Slice aliases.Piece) :
  Result (alloc.vec.Vec aliases.Piece)
  := do
  aliases.to_ids_loop table pieces (alloc.vec.Vec.new aliases.Piece) 0#usize

/-- [timeways_rules::aliases::to_name]:
    Source: 'crates/rules/src/aliases.rs', lines 98:0-109:1 -/
def aliases.to_name
  (table : Slice aliases.Alias) (piece : aliases.Piece) :
  Result aliases.Piece
  := do
  match piece with
  | aliases.Piece.Text _ => aliases.Piece.Insts.CoreCloneClone.clone piece
  | aliases.Piece.Word _ _ => aliases.Piece.Insts.CoreCloneClone.clone piece
  | aliases.Piece.Player id =>
    let i := Slice.len table
    if id < i
    then
      let «alias» ← Slice.index_usize table id
      let s ← alloc.string.String.Insts.CoreCloneClone.clone «alias».key
      let s1 ← alloc.string.String.Insts.CoreCloneClone.clone «alias».shown
      ok (aliases.Piece.Word s s1)
    else aliases.Piece.Insts.CoreCloneClone.clone (aliases.Piece.Player id)

/-- [timeways_rules::aliases::to_names]: loop 0:
    Source: 'crates/rules/src/aliases.rs', lines 118:4-121:5
    Visibility: public -/
@[rust_loop]
def aliases.to_names_loop
  (table : Slice aliases.Alias) (pieces : Slice aliases.Piece)
  (swapped : alloc.vec.Vec aliases.Piece) (index : Std.Usize) :
  Result (alloc.vec.Vec aliases.Piece)
  := do
  let i := Slice.len pieces
  if index < i
  then
    let p ← Slice.index_usize pieces index
    let p1 ← aliases.to_name table p
    let swapped1 ← alloc.vec.Vec.push swapped p1
    let index1 ← index + 1#usize
    aliases.to_names_loop table pieces swapped1 index1
  else ok swapped
partial_fixpoint

/-- [timeways_rules::aliases::to_names]:
    Source: 'crates/rules/src/aliases.rs', lines 115:0-123:1
    Visibility: public -/
@[reducible]
def aliases.to_names
  (table : Slice aliases.Alias) (pieces : Slice aliases.Piece) :
  Result (alloc.vec.Vec aliases.Piece)
  := do
  aliases.to_names_loop table pieces (alloc.vec.Vec.new aliases.Piece) 0#usize

/-- [timeways_rules::budget::HOUR]
    Source: 'crates/rules/src/budget.rs', lines 5:0-5:23 -/
@[global_simps, irreducible] def budget.HOUR : Std.U64 := 3600#u64

/-- [timeways_rules::budget::{timeways_rules::budget::Budget}::take]:
    Source: 'crates/rules/src/budget.rs', lines 16:4-29:5
    Visibility: public -/
def budget.Budget.take
  (self : budget.Budget) («at» : Std.U64) :
  Result (Bool × budget.Budget)
  := do
  let oldest ← Array.index_usize self.spoken 0#usize
  let too_soon ←
    match oldest with
    | none => ok false
    | some oldest1 =>
      do
      let i ← lift (core.num.U64.saturating_sub «at» oldest1)
      ok (i < budget.HOUR)
  if too_soon
  then ok (false, self)
  else
    let o ← Array.index_usize self.spoken 1#usize
    let o1 ← Array.index_usize self.spoken 2#usize
    ok (true, { spoken := (Array.make 3#usize [ o, o1, some «at» ]) })

/-- [timeways_rules::chapters::AWAY_SECONDS]
    Source: 'crates/rules/src/chapters.rs', lines 16:0-16:39
    Visibility: public -/
@[global_simps, irreducible]
def chapters.AWAY_SECONDS : Result Std.U64 := 8#u64 * 3600#u64

/-- [timeways_rules::chapters::RUN_GAP_SECONDS]
    Source: 'crates/rules/src/chapters.rs', lines 20:0-20:41
    Visibility: public -/
@[global_simps, irreducible]
def chapters.RUN_GAP_SECONDS : Result Std.U64 := 30#u64 * 60#u64

/-- [timeways_rules::chapters::UNSEEN]
    Source: 'crates/rules/src/chapters.rs', lines 179:0-183:2 -/
@[global_simps, irreducible]
def chapters.UNSEEN : chapters.KeyRecord :=
  { seen := false, deaths := 0#u8, gain := 0#u16 }

/-- [timeways_rules::chapters::UNBEATEN]
    Source: 'crates/rules/src/chapters.rs', lines 185:0-188:2 -/
@[global_simps, irreducible]
def chapters.UNBEATEN : chapters.FoeRecord :=
  { beaten := false, deaths := 0#u8 }

/-- [timeways_rules::chapters::UNSETTLED]
    Source: 'crates/rules/src/chapters.rs', lines 190:0-193:2 -/
@[global_simps, irreducible]
def chapters.UNSETTLED : chapters.ZoneRecord :=
  { settled := false, last_chapter := 0#usize }

/-- [timeways_rules::weights::RULE_ONE]
    Source: 'crates/rules/src/weights.rs', lines 6:0-6:27
    Visibility: public -/
@[global_simps, irreducible] def weights.RULE_ONE : Std.U8 := 1#u8

/-- [timeways_rules::chapters::start]:
    Source: 'crates/rules/src/chapters.rs', lines 198:0-218:1
    Visibility: public -/
def chapters.start : Result chapters.Fold := do
  ok
    {
      keys := (alloc.vec.Vec.new chapters.KeyRecord),
      foes := (alloc.vec.Vec.new chapters.FoeRecord),
      zones := (alloc.vec.Vec.new chapters.ZoneRecord),
      closed := (alloc.vec.Vec.new chapters.ClosedChapter),
      «open» :=
        {
          first := 0#usize,
          weight := 0#u16,
          opening := chapters.Opening.First,
          zone := none,
          rule := weights.RULE_ONE
        },
      pending := none,
      tales := (alloc.vec.Vec.new chapters.Tale),
      visits := (alloc.vec.Vec.new chapters.Visit),
      visit := none,
      last_at := none,
      gains := (alloc.vec.Vec.new chapters.Gain)
    }

/-- [timeways_rules::chapters::add_to_visit]:
    Source: 'crates/rules/src/chapters.rs', lines 567:0-574:1 -/
def chapters.add_to_visit
  (fold : chapters.Fold) (amount : Std.U16) : Result chapters.Fold := do
  match fold.visit with
  | none => ok fold
  | some visit =>
    let i ← lift (UScalar.cast .U32 amount)
    let i1 ← lift (core.num.U32.saturating_add visit.gain i)
    ok { fold with visit := (some { visit with gain := i1 }) }

/-- [timeways_rules::chapters::close_visit]:
    Source: 'crates/rules/src/chapters.rs', lines 552:0-563:1 -/
def chapters.close_visit
  (fold : chapters.Fold) (visit : chapters.Visit) : Result chapters.Fold := do
  let v ← alloc.vec.Vec.push fold.visits visit
  let i := alloc.vec.Vec.len fold.tales
  if visit.tale < i
  then
    let tale ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice chapters.Tale)
        fold.tales visit.tale
    let i1 ← lift (core.num.U32.saturating_add tale.weight visit.gain)
    let i2 ← lift (core.num.U32.saturating_add tale.runs 1#u32)
    let (_, index_mut_back) ←
      alloc.vec.Vec.index_mut (core.slice.index.SliceIndexUsizeSlice
        chapters.Tale) fold.tales visit.tale
    let v1 := index_mut_back { tale with weight := i1, runs := i2 }
    ok { fold with tales := v1, visits := v, visit := none }
  else ok { fold with visits := v, visit := none }

/-- [timeways_rules::chapters::tale_of]: loop 0:
    Source: 'crates/rules/src/chapters.rs', lines 536:4-549:1 -/
@[rust_loop]
def chapters.tale_of_loop
  (fold : chapters.Fold) («instance» : Std.Usize) (here : Std.Usize)
  (index : Std.Usize) :
  Result (Std.Usize × (alloc.vec.Vec chapters.KeyRecord) × (alloc.vec.Vec
    chapters.FoeRecord) × (alloc.vec.Vec chapters.ZoneRecord) ×
    (alloc.vec.Vec chapters.ClosedChapter) × chapters.Chapter × (Option
    chapters.Break) × (alloc.vec.Vec chapters.Tale) × (alloc.vec.Vec
    chapters.Visit) × (Option chapters.Visit) × (Option Std.U64) ×
    (alloc.vec.Vec chapters.Gain))
  := do
  let i := alloc.vec.Vec.len fold.tales
  if index < i
  then
    let t ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice chapters.Tale)
        fold.tales index
    if t.instance = «instance»
    then
      ok (index, fold.keys, fold.foes, fold.zones, fold.closed, fold.open,
        fold.pending, fold.tales, fold.visits, fold.visit, fold.last_at,
        fold.gains)
    else
      let index1 ← index + 1#usize
      chapters.tale_of_loop fold «instance» here index1
  else
    let v ←
      alloc.vec.Vec.push fold.tales
        ({ «instance», first := here, weight := 0#u32, runs := 0#u32 } :
        chapters.Tale)
    ok (index, fold.keys, fold.foes, fold.zones, fold.closed, fold.open,
      fold.pending, v, fold.visits, fold.visit, fold.last_at, fold.gains)
partial_fixpoint

/-- [timeways_rules::chapters::tale_of]:
    Source: 'crates/rules/src/chapters.rs', lines 534:0-549:1 -/
def chapters.tale_of
  (fold : chapters.Fold) («instance» : Std.Usize) (here : Std.Usize) :
  Result (Std.Usize × chapters.Fold)
  := do
  let (i, v, v1, v2, v3, c, o, v4, v5, o1, o2, v6) ←
    chapters.tale_of_loop fold «instance» here 0#usize
  ok (i,
    {
      keys := v,
      foes := v1,
      zones := v2,
      closed := v3,
      «open» := c,
      pending := o,
      tales := v4,
      visits := v5,
      visit := o1,
      last_at := o2,
      gains := v6
    })

/-- [timeways_rules::chapters::enter_instance]:
    Source: 'crates/rules/src/chapters.rs', lines 509:0-530:1 -/
def chapters.enter_instance
  (fold : chapters.Fold) («instance» : Std.Usize) (here : Std.Usize)
  («at» : Std.U64) :
  Result chapters.Fold
  := do
  let (tale, fold1) ← chapters.tale_of fold «instance» here
  match fold1.visit with
  | none =>
    ok
      {
        fold1
          with
          visit :=
            (some
              {
                tale,
                first := here,
                last := here,
                left_at := «at»,
                gain := 0#u32
              })
      }
  | some visit =>
    let resumed ←
      if visit.tale = tale
      then
        do
        let i ← chapters.RUN_GAP_SECONDS
        let i1 ← lift (core.num.U64.saturating_add visit.left_at i)
        ok («at» < i1)
      else ok false
    if resumed
    then
      ok
        {
          fold1
            with
            visit := (some { visit with last := here, left_at := «at» })
        }
    else
      let fold2 ← chapters.close_visit fold1 visit
      ok
        {
          fold2
            with
            visit :=
              (some
                {
                  tale,
                  first := here,
                  last := here,
                  left_at := «at»,
                  gain := 0#u32
                })
        }

/-- [timeways_rules::chapters::leave_instance]:
    Source: 'crates/rules/src/chapters.rs', lines 499:0-505:1 -/
def chapters.leave_instance
  (fold : chapters.Fold) («at» : Std.U64) : Result chapters.Fold := do
  match fold.visit with
  | none => ok fold
  | some visit =>
    let i ← chapters.RUN_GAP_SECONDS
    let i1 ← lift (core.num.U64.saturating_add visit.left_at i)
    if «at» >= i1
    then chapters.close_visit fold visit
    else ok fold

/-- [timeways_rules::weights::CAP_MAX]
    Source: 'crates/rules/src/weights.rs', lines 9:0-9:27
    Visibility: public -/
@[global_simps, irreducible] def weights.CAP_MAX : Std.U16 := 7#u16

/-- [timeways_rules::weights::death_weight]:
    Source: 'crates/rules/src/weights.rs', lines 80:0-87:1
    Visibility: public -/
def weights.death_weight
  (rule : Std.U8) (deaths : Std.U8) : Result Std.U16 := do
  match deaths with
  | 0#uscalar => ok 2#u16
  | 1#uscalar => ok 1#u16
  | _ => ok 0#u16

/-- [timeways_rules::weights::DEATHS_COUNTED]
    Source: 'crates/rules/src/weights.rs', lines 15:0-15:33
    Visibility: public -/
@[global_simps, irreducible] def weights.DEATHS_COUNTED : Std.U8 := 2#u8

/-- [timeways_rules::chapters::one_more_death]:
    Source: 'crates/rules/src/chapters.rs', lines 490:0-496:1 -/
def chapters.one_more_death (deaths : Std.U8) : Result Std.U8 := do
  if deaths < weights.DEATHS_COUNTED
  then deaths + 1#u8
  else ok deaths

/-- [timeways_rules::chapters::has_slot]:
    Source: 'crates/rules/src/chapters.rs', lines 405:0-407:1 -/
def chapters.has_slot (length : Std.Usize) (id : Std.Usize) : Result Bool := do
  if id < length
  then ok true
  else if id = length
       then ok (length < core.num.Usize.MAX)
       else ok false

/-- [timeways_rules::chapters::death_gain]:
    Source: 'crates/rules/src/chapters.rs', lines 466:0-488:1 -/
def chapters.death_gain
  (fold : chapters.Fold) (record : chapters.KeyRecord) (foe : Option Std.Usize)
  (rule : Std.U8) :
  Result (Std.U16 × chapters.Fold × chapters.KeyRecord)
  := do
  match foe with
  | none =>
    let gain ← weights.death_weight rule record.deaths
    let i ← chapters.one_more_death record.deaths
    ok (gain, fold, { record with deaths := i })
  | some foe1 =>
    let i := alloc.vec.Vec.len fold.foes
    let b ← chapters.has_slot i foe1
    if b
    then
      let i1 := alloc.vec.Vec.len fold.foes
      let v ←
        if foe1 = i1
        then alloc.vec.Vec.push fold.foes chapters.UNBEATEN
        else ok fold.foes
      let before ←
        alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice
          chapters.FoeRecord) v foe1
      let i2 ← chapters.one_more_death before.deaths
      let (_, index_mut_back) ←
        alloc.vec.Vec.index_mut (core.slice.index.SliceIndexUsizeSlice
          chapters.FoeRecord) v foe1
      if before.beaten
      then
        let v1 := index_mut_back { beaten := true, deaths := i2 }
        ok (0#u16, { fold with foes := v1 }, record)
      else
        let gain ← weights.death_weight rule before.deaths
        let v1 := index_mut_back { beaten := false, deaths := i2 }
        ok (gain, { fold with foes := v1 }, record)
    else ok (0#u16, fold, record)

/-- [timeways_rules::weights::REVENGE]
    Source: 'crates/rules/src/weights.rs', lines 12:0-12:27
    Visibility: public -/
@[global_simps, irreducible] def weights.REVENGE : Std.U16 := 2#u16

/-- [timeways_rules::weights::weight]:
    Source: 'crates/rules/src/weights.rs', lines 55:0-76:1
    Visibility: public -/
def weights.weight
  (rule : Std.U8) (kind : weights.KeyKind) : Result Std.U16 := do
  match kind with
  | weights.KeyKind.GameQuest => ok 1#u16
  | weights.KeyKind.SideQuest => ok 2#u16
  | weights.KeyKind.ClassQuest => ok 3#u16
  | weights.KeyKind.Subzone => ok 1#u16
  | weights.KeyKind.Level => ok 2#u16
  | weights.KeyKind.Talk => ok 1#u16
  | weights.KeyKind.Kill => ok 3#u16
  | weights.KeyKind.RaidKill => ok 5#u16
  | weights.KeyKind.Death => ok 0#u16
  | weights.KeyKind.Mark => ok 1#u16
  | weights.KeyKind.Title => ok 1#u16
  | weights.KeyKind.Mount => ok 3#u16
  | weights.KeyKind.EpicMount => ok 5#u16
  | weights.KeyKind.EpicItem => ok 3#u16
  | weights.KeyKind.Upgrade => ok 1#u16
  | weights.KeyKind.PvpRank => ok 2#u16
  | weights.KeyKind.Dungeon => ok 3#u16
  | weights.KeyKind.Raid => ok 5#u16
  | weights.KeyKind.Battleground => ok 3#u16
  | weights.KeyKind.BgWin => ok 3#u16

/-- [timeways_rules::chapters::first_time_gain]:
    Source: 'crates/rules/src/chapters.rs', lines 436:0-438:1 -/
def chapters.first_time_gain
  (record : chapters.KeyRecord) (kind : weights.KeyKind) (rule : Std.U8) :
  Result Std.U16
  := do
  if record.seen
  then ok 0#u16
  else weights.weight rule kind

/-- [timeways_rules::chapters::kill_gain]:
    Source: 'crates/rules/src/chapters.rs', lines 442:0-462:1 -/
def chapters.kill_gain
  (fold : chapters.Fold) (record : chapters.KeyRecord) (key : chapters.Key)
  (rule : Std.U8) :
  Result ((Std.U16 × Bool) × chapters.Fold)
  := do
  let base ← chapters.first_time_gain record key.kind rule
  match key.foe with
  | none => ok ((base, false), fold)
  | some foe =>
    let i := alloc.vec.Vec.len fold.foes
    let b ← chapters.has_slot i foe
    if b
    then
      let i1 := alloc.vec.Vec.len fold.foes
      let v ←
        if foe = i1
        then alloc.vec.Vec.push fold.foes chapters.UNBEATEN
        else ok fold.foes
      let before ←
        alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice
          chapters.FoeRecord) v foe
      let (_, index_mut_back) ←
        alloc.vec.Vec.index_mut (core.slice.index.SliceIndexUsizeSlice
          chapters.FoeRecord) v foe
      if record.seen
      then
        let v1 := index_mut_back { before with beaten := true }
        ok ((base, false), { fold with foes := v1 })
      else
        if before.beaten
        then
          let v1 := index_mut_back before
          ok ((base, false), { fold with foes := v1 })
        else
          if before.deaths = 0#u8
          then
            let v1 := index_mut_back { before with beaten := true }
            ok ((base, false), { fold with foes := v1 })
          else
            let i2 ← base + weights.REVENGE
            let v1 := index_mut_back { before with beaten := true }
            ok ((i2, true), { fold with foes := v1 })
    else ok ((base, false), fold)

/-- [timeways_rules::chapters::gain_of]:
    Source: 'crates/rules/src/chapters.rs', lines 411:0-434:1 -/
def chapters.gain_of
  (fold : chapters.Fold) (key : Option chapters.Key) :
  Result ((Std.U16 × Bool) × chapters.Fold)
  := do
  match key with
  | none => ok ((0#u16, false), fold)
  | some key1 =>
    let i := alloc.vec.Vec.len fold.keys
    let b ← chapters.has_slot i key1.id
    if b
    then
      let i1 := alloc.vec.Vec.len fold.keys
      let v ←
        if key1.id = i1
        then alloc.vec.Vec.push fold.keys chapters.UNSEEN
        else ok fold.keys
      let record ←
        alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice
          chapters.KeyRecord) v key1.id
      let (fold1, record1, (raw, revenge)) ←
        match key1.kind with
        | weights.KeyKind.GameQuest =>
          do
          let i2 ←
            chapters.first_time_gain record weights.KeyKind.GameQuest
              fold.open.rule
          ok ({ fold with keys := v }, record, (i2, false))
        | weights.KeyKind.SideQuest =>
          do
          let i2 ←
            chapters.first_time_gain record weights.KeyKind.SideQuest
              fold.open.rule
          ok ({ fold with keys := v }, record, (i2, false))
        | weights.KeyKind.ClassQuest =>
          do
          let i2 ←
            chapters.first_time_gain record weights.KeyKind.ClassQuest
              fold.open.rule
          ok ({ fold with keys := v }, record, (i2, false))
        | weights.KeyKind.Subzone =>
          do
          let i2 ←
            chapters.first_time_gain record weights.KeyKind.Subzone
              fold.open.rule
          ok ({ fold with keys := v }, record, (i2, false))
        | weights.KeyKind.Level =>
          do
          let i2 ←
            chapters.first_time_gain record weights.KeyKind.Level
              fold.open.rule
          ok ({ fold with keys := v }, record, (i2, false))
        | weights.KeyKind.Talk =>
          do
          let i2 ←
            chapters.first_time_gain record weights.KeyKind.Talk fold.open.rule
          ok ({ fold with keys := v }, record, (i2, false))
        | weights.KeyKind.Kill =>
          do
          let (p, fold2) ←
            chapters.kill_gain { fold with keys := v } record key1
              fold.open.rule
          ok (fold2, record, p)
        | weights.KeyKind.RaidKill =>
          do
          let (p, fold2) ←
            chapters.kill_gain { fold with keys := v } record key1
              fold.open.rule
          ok (fold2, record, p)
        | weights.KeyKind.Death =>
          do
          let (i2, fold2, record2) ←
            chapters.death_gain { fold with keys := v } record key1.foe
              fold.open.rule
          ok (fold2, record2, (i2, false))
        | weights.KeyKind.Mark =>
          do
          let i2 ←
            chapters.first_time_gain record weights.KeyKind.Mark fold.open.rule
          ok ({ fold with keys := v }, record, (i2, false))
        | weights.KeyKind.Title =>
          do
          let i2 ←
            chapters.first_time_gain record weights.KeyKind.Title
              fold.open.rule
          ok ({ fold with keys := v }, record, (i2, false))
        | weights.KeyKind.Mount =>
          do
          let i2 ←
            chapters.first_time_gain record weights.KeyKind.Mount
              fold.open.rule
          ok ({ fold with keys := v }, record, (i2, false))
        | weights.KeyKind.EpicMount =>
          do
          let i2 ←
            chapters.first_time_gain record weights.KeyKind.EpicMount
              fold.open.rule
          ok ({ fold with keys := v }, record, (i2, false))
        | weights.KeyKind.EpicItem =>
          do
          let i2 ←
            chapters.first_time_gain record weights.KeyKind.EpicItem
              fold.open.rule
          ok ({ fold with keys := v }, record, (i2, false))
        | weights.KeyKind.Upgrade =>
          do
          let i2 ←
            chapters.first_time_gain record weights.KeyKind.Upgrade
              fold.open.rule
          ok ({ fold with keys := v }, record, (i2, false))
        | weights.KeyKind.PvpRank =>
          do
          let i2 ←
            chapters.first_time_gain record weights.KeyKind.PvpRank
              fold.open.rule
          ok ({ fold with keys := v }, record, (i2, false))
        | weights.KeyKind.Dungeon =>
          do
          let i2 ←
            chapters.first_time_gain record weights.KeyKind.Dungeon
              fold.open.rule
          ok ({ fold with keys := v }, record, (i2, false))
        | weights.KeyKind.Raid =>
          do
          let i2 ←
            chapters.first_time_gain record weights.KeyKind.Raid fold.open.rule
          ok ({ fold with keys := v }, record, (i2, false))
        | weights.KeyKind.Battleground =>
          do
          let i2 ←
            chapters.first_time_gain record weights.KeyKind.Battleground
              fold.open.rule
          ok ({ fold with keys := v }, record, (i2, false))
        | weights.KeyKind.BgWin =>
          do
          let i2 ←
            chapters.first_time_gain record weights.KeyKind.BgWin
              fold.open.rule
          ok ({ fold with keys := v }, record, (i2, false))
      let room ←
        lift (core.num.U16.saturating_sub weights.CAP_MAX record1.gain)
      let amount ← if raw < room
                     then ok raw
                     else ok room
      let i2 ← lift (core.num.U16.saturating_add record1.gain amount)
      let (_, index_mut_back) ←
        alloc.vec.Vec.index_mut (core.slice.index.SliceIndexUsizeSlice
          chapters.KeyRecord) fold1.keys key1.id
      let v1 := index_mut_back { record1 with seen := true, gain := i2 }
      ok ((amount, revenge), { fold1 with keys := v1 })
    else ok ((0#u16, false), fold)

/-- [timeways_rules::weights::limits]:
    Source: 'crates/rules/src/weights.rs', lines 90:0-93:1
    Visibility: public -/
def weights.limits (rule : Std.U8) : Result weights.Limits := do
  ok { min := 15#u16, max := 40#u16 }

/-- [timeways_rules::chapters::settle]:
    Source: 'crates/rules/src/chapters.rs', lines 394:0-401:1 -/
def chapters.settle
  (fold : chapters.Fold) (zone : Std.Usize) : Result chapters.Fold := do
  let i := alloc.vec.Vec.len fold.zones
  if zone < i
  then
    let i1 := alloc.vec.Vec.len fold.closed
    let (_, index_mut_back) ←
      alloc.vec.Vec.index_mut (core.slice.index.SliceIndexUsizeSlice
        chapters.ZoneRecord) fold.zones zone
    let v := index_mut_back { settled := true, last_chapter := i1 }
    ok { fold with zones := v }
  else ok fold

/-- [timeways_rules::chapters::zone_break]:
    Source: 'crates/rules/src/chapters.rs', lines 377:0-392:1 -/
def chapters.zone_break
  (fold : chapters.Fold) (zone : Std.Usize) :
  Result ((Option chapters.Break) × chapters.Fold)
  := do
  let i := alloc.vec.Vec.len fold.zones
  let b ← chapters.has_slot i zone
  if b
  then
    let i1 := alloc.vec.Vec.len fold.zones
    let v ←
      if zone = i1
      then alloc.vec.Vec.push fold.zones chapters.UNSETTLED
      else ok fold.zones
    let record ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice
        chapters.ZoneRecord) v zone
    if record.settled
    then
      let i2 ←
        lift (core.num.Usize.saturating_add record.last_chapter 1#usize)
      let i3 := alloc.vec.Vec.len fold.closed
      if i2 < i3
      then ok (some chapters.Break.Return, { fold with zones := v })
      else ok (none, { fold with zones := v })
    else ok (some chapters.Break.NewZone, { fold with zones := v })
  else ok (none, fold)

/-- [timeways_rules::chapters::close_chapter]:
    Source: 'crates/rules/src/chapters.rs', lines 324:0-331:1 -/
def chapters.close_chapter
  (fold : chapters.Fold) (last : Std.Usize) (close : chapters.Close) :
  Result chapters.Fold
  := do
  let v ←
    alloc.vec.Vec.push fold.closed ({ chapter := fold.open, last, close } :
      chapters.ClosedChapter)
  ok { fold with closed := v }

/-- [timeways_rules::chapters::title_rank]:
    Source: 'crates/rules/src/chapters.rs', lines 313:0-322:1 -/
def chapters.title_rank (cut : chapters.Break) : Result Std.U8 := do
  match cut with
  | chapters.Break.Return => ok 0#u8
  | chapters.Break.NewZone => ok 1#u8
  | chapters.Break.Level => ok 2#u8
  | chapters.Break.Capital => ok 3#u8
  | chapters.Break.Inn => ok 4#u8
  | chapters.Break.Away => ok 5#u8

/-- [timeways_rules::chapters::wait_for_cut]:
    Source: 'crates/rules/src/chapters.rs', lines 298:0-311:1 -/
def chapters.wait_for_cut
  (fold : chapters.Fold) (new : chapters.Break) : Result chapters.Fold := do
  match fold.pending with
  | none => ok { fold with pending := (some new) }
  | some old =>
    let i ← chapters.title_rank old
    let i1 ← chapters.title_rank new
    if i <= i1
    then ok fold
    else ok { fold with pending := (some new) }

/-- [timeways_rules::chapters::add_to_chapter]:
    Source: 'crates/rules/src/chapters.rs', lines 335:0-373:1 -/
def chapters.add_to_chapter
  (fold : chapters.Fold) (zone : Std.Usize) (amount : Std.U16)
  (here : Std.Usize) :
  Result chapters.Fold
  := do
  if amount = 0#u16
  then ok fold
  else
    let (o, fold1) ← chapters.zone_break fold zone
    let fold2 ←
      match o with
      | none => ok fold1
      | some cut => chapters.wait_for_cut fold1 cut
    let bounds ← weights.limits fold2.open.rule
    let (v, v1, v2, v3, i, i1, o1, o2, o3, v4, v5, o4, o5, v6, bounds1) ←
      match fold2.pending with
      | none =>
        ok (fold2.keys, fold2.foes, fold2.zones, fold2.closed,
          fold2.open.first, fold2.open.weight, fold2.open.opening,
          fold2.open.zone, none, fold2.tales, fold2.visits, fold2.visit,
          fold2.last_at, fold2.gains, bounds)
      | some cut =>
        do
        let (v7, v8, v9, v10, i2, i3, o6, o7, o8, v11, v12, o9, o10, v13) ←
          if fold2.open.weight >= bounds.min
          then
            if fold2.open.first < here
            then
              do
              let i4 ← here - 1#usize
              let fold3 ←
                chapters.close_chapter { fold2 with pending := none } i4
                  chapters.Close.Break
              ok (fold3.keys, fold3.foes, fold3.zones, fold3.closed, here,
                0#u16, chapters.Opening.Break cut, some zone, fold3.pending,
                fold3.tales, fold3.visits, fold3.visit, fold3.last_at,
                fold3.gains)
            else
              ok (fold2.keys, fold2.foes, fold2.zones, fold2.closed,
                fold2.open.first, fold2.open.weight, fold2.open.opening,
                fold2.open.zone, none, fold2.tales, fold2.visits, fold2.visit,
                fold2.last_at, fold2.gains)
          else
            ok (fold2.keys, fold2.foes, fold2.zones, fold2.closed,
              fold2.open.first, fold2.open.weight, fold2.open.opening,
              fold2.open.zone, none, fold2.tales, fold2.visits, fold2.visit,
              fold2.last_at, fold2.gains)
        ok (v7, v8, v9, v10, i2, i3, o6, o7, o8, v11, v12, o9, o10, v13,
          bounds)
    let i2 ← lift (core.num.U16.saturating_add i1 amount)
    let b := core.option.Option.is_none o2
    let o6 ← if b
               then ok (some zone)
               else ok o2
    let fold3 ←
      chapters.settle
        {
          keys := v,
          foes := v1,
          zones := v2,
          closed := v3,
          «open» :=
            {
              fold2.open
                with
                first := i, weight := i2, opening := o1, zone := o6
            },
          pending := o3,
          tales := v4,
          visits := v5,
          visit := o4,
          last_at := o5,
          gains := v6
        } zone
    if fold3.open.weight >= bounds1.max
    then
      let fold4 ← chapters.close_chapter fold3 here chapters.Close.Max
      let i3 ← here + 1#usize
      ok
        {
          fold4
            with
            «open» :=
              {
                fold2.open
                  with
                  first := i3,
                  weight := 0#u16,
                  opening := chapters.Opening.Max,
                  zone := (some zone)
              }
        }
    else ok fold3

/-- [timeways_rules::chapters::apply_play]:
    Source: 'crates/rules/src/chapters.rs', lines 270:0-295:1 -/
def chapters.apply_play
  (fold : chapters.Fold) (play : chapters.Play) : Result chapters.Fold := do
  let here := alloc.vec.Vec.len fold.gains
  let (fold1, play1) ←
    match fold.last_at with
    | none => ok (fold, play)
    | some last =>
      do
      let i ← chapters.AWAY_SECONDS
      let i1 ← lift (core.num.U64.saturating_add last i)
      let f ←
        if play.at >= i1
        then chapters.wait_for_cut fold chapters.Break.Away
        else ok fold
      ok (f, play)
  let fold2 ←
    match play1.mark with
    | none => ok fold1
    | some mark => chapters.wait_for_cut fold1 mark
  let (fold3, t) ←
    match play1.track with
    | chapters.Track.World =>
      do
      let fold4 ← chapters.leave_instance fold2 play1.at
      ok (fold4, chapters.Track.World)
    | chapters.Track.Instance «instance» =>
      do
      let fold4 ← chapters.enter_instance fold2 «instance» here play1.at
      ok (fold4, play1.track)
  let ((amount, revenge), fold4) ← chapters.gain_of fold3 play1.key
  let fold5 ←
    match t with
    | chapters.Track.World =>
      chapters.add_to_chapter fold4 play1.zone amount here
    | chapters.Track.Instance _ => chapters.add_to_visit fold4 amount
  let v ←
    alloc.vec.Vec.push fold5.gains ({ amount, track := t, revenge } :
      chapters.Gain)
  ok { fold5 with last_at := (some play1.at), gains := v }

/-- [timeways_rules::chapters::apply_rule]:
    Source: 'crates/rules/src/chapters.rs', lines 248:0-268:1 -/
def chapters.apply_rule
  (fold : chapters.Fold) (rule : Std.U8) : Result chapters.Fold := do
  let here := alloc.vec.Vec.len fold.gains
  let (v, v1, v2, v3, i, i1, o, o1, v4, v5, o2, o3, v6) ←
    if fold.open.first < here
    then
      do
      let i2 ← here - 1#usize
      let fold1 ← chapters.close_chapter fold i2 chapters.Close.Rule
      ok (fold1.keys, fold1.foes, fold1.zones, fold1.closed, here, 0#u16,
        chapters.Opening.Rule, none, fold1.tales, fold1.visits, fold1.visit,
        fold1.last_at, fold1.gains)
    else
      ok (fold.keys, fold.foes, fold.zones, fold.closed, fold.open.first,
        fold.open.weight, fold.open.opening, fold.open.zone, fold.tales,
        fold.visits, fold.visit, fold.last_at, fold.gains)
  let v7 ←
    alloc.vec.Vec.push v6
      ({ amount := 0#u16, track := chapters.Track.World, revenge := false } :
      chapters.Gain)
  ok
    {
      keys := v,
      foes := v1,
      zones := v2,
      closed := v3,
      «open» := { first := i, weight := i1, opening := o, zone := o1, rule },
      pending := none,
      tales := v4,
      visits := v5,
      visit := o2,
      last_at := o3,
      gains := v7
    }

/-- [timeways_rules::chapters::apply]:
    Source: 'crates/rules/src/chapters.rs', lines 239:0-244:1 -/
def chapters.apply
  (fold : chapters.Fold) (step : chapters.Step) : Result chapters.Fold := do
  match step with
  | chapters.Step.Play play => chapters.apply_play fold play
  | chapters.Step.Rule rule => chapters.apply_rule fold rule

/-- [timeways_rules::chapters::advance]: loop 0:
    Source: 'crates/rules/src/chapters.rs', lines 233:4-236:5
    Visibility: public -/
@[rust_loop]
def chapters.advance_loop
  (fold : chapters.Fold) (steps : Slice chapters.Step) (index : Std.Usize) :
  Result chapters.Fold
  := do
  let i := Slice.len steps
  if index < i
  then
    let s ← Slice.index_usize steps index
    let fold1 ← chapters.apply fold s
    let index1 ← index + 1#usize
    chapters.advance_loop fold1 steps index1
  else ok fold
partial_fixpoint

/-- [timeways_rules::chapters::advance]:
    Source: 'crates/rules/src/chapters.rs', lines 231:0-237:1
    Visibility: public -/
@[reducible]
def chapters.advance
  (fold : chapters.Fold) (steps : Slice chapters.Step) :
  Result chapters.Fold
  := do
  chapters.advance_loop fold steps 0#usize

/-- [timeways_rules::chapters::chapters]:
    Source: 'crates/rules/src/chapters.rs', lines 223:0-227:1
    Visibility: public -/
def chapters.chapters
  (steps : Slice chapters.Step) : Result chapters.Fold := do
  let fold ← chapters.start
  chapters.advance fold steps

/-- [timeways_rules::entry_edits::newest_row]: loop 0:
    Source: 'crates/rules/src/entry_edits.rs', lines 43:4-53:5
    Visibility: public -/
@[rust_loop]
def entry_edits.newest_row_loop
  (rows : Slice Std.U64) (newest : Option Std.U64) (index : Std.Usize) :
  Result (Option Std.U64)
  := do
  let i := Slice.len rows
  if index < i
  then
    let row ← Slice.index_usize rows index
    let older ←
      match newest with
      | none => ok false
      | some best => ok (best > row)
    let newest1 ← if older
                    then ok newest
                    else ok (some row)
    let index1 ← index + 1#usize
    entry_edits.newest_row_loop rows newest1 index1
  else ok newest
partial_fixpoint

/-- [timeways_rules::entry_edits::newest_row]:
    Source: 'crates/rules/src/entry_edits.rs', lines 40:0-55:1
    Visibility: public -/
@[reducible]
def entry_edits.newest_row
  (rows : Slice Std.U64) : Result (Option Std.U64) := do
  entry_edits.newest_row_loop rows none 0#usize

/-- [timeways_rules::entry_edits::newest_edit]: loop 0:
    Source: 'crates/rules/src/entry_edits.rs', lines 62:4-72:5
    Visibility: public -/
@[rust_loop]
def entry_edits.newest_edit_loop
  (edits : Slice entry_edits.EditRow) (newest : Option entry_edits.EditRow)
  (index : Std.Usize) :
  Result (Option entry_edits.EditRow)
  := do
  let i := Slice.len edits
  if index < i
  then
    let edit ← Slice.index_usize edits index
    let (newest1, edit1, older) ←
      match newest with
      | none => ok (none, edit, false)
      | some best => ok (newest, edit, best.row > edit.row)
    let newest2 ← if older
                    then ok newest1
                    else ok (some edit1)
    let index1 ← index + 1#usize
    entry_edits.newest_edit_loop edits newest2 index1
  else ok newest
partial_fixpoint

/-- [timeways_rules::entry_edits::newest_edit]:
    Source: 'crates/rules/src/entry_edits.rs', lines 59:0-74:1
    Visibility: public -/
@[reducible]
def entry_edits.newest_edit
  (edits : Slice entry_edits.EditRow) :
  Result (Option entry_edits.EditRow)
  := do
  entry_edits.newest_edit_loop edits none 0#usize

/-- [timeways_rules::entry_edits::shown]:
    Source: 'crates/rules/src/entry_edits.rs', lines 79:0-106:1
    Visibility: public -/
def entry_edits.shown
  (narrator_rows : Slice Std.U64) (edits : Slice entry_edits.EditRow) :
  Result entry_edits.Shown
  := do
  let narrator ← entry_edits.newest_row narrator_rows
  let o ← entry_edits.newest_edit edits
  match o with
  | none => ok { title := none, narrator, player := none }
  | some edit =>
    let title ← if edit.has_title
                  then ok (some edit.row)
                  else ok none
    match edit.text with
    | entry_edits.EditText.Keep =>
      ok { title, narrator, player := (some edit.row) }
    | entry_edits.EditText.Replace =>
      ok { title, narrator := none, player := (some edit.row) }
    | entry_edits.EditText.Narrator => ok { title, narrator, player := none }

/-- [timeways_rules::hero_hook::HOOK_EVERY]
    Source: 'crates/rules/src/hero_hook.rs', lines 4:0-4:30
    Visibility: public -/
@[global_simps, irreducible] def hero_hook.HOOK_EVERY : Std.U64 := 3#u64

/-- [timeways_rules::hero_hook::applies]:
    Source: 'crates/rules/src/hero_hook.rs', lines 10:0-12:1
    Visibility: public -/
def hero_hook.applies (count : Std.U64) : Result Bool := do
  let i ← count % hero_hook.HOOK_EVERY
  let i1 ← hero_hook.HOOK_EVERY - 1#u64
  ok (i = i1)

/-- [timeways_rules::hero_hook::pick]:
    Source: 'crates/rules/src/hero_hook.rs', lines 18:0-29:1
    Visibility: public -/
def hero_hook.pick
  (filled : Std.Usize) (count : Std.U64) : Result (Option Std.Usize) := do
  let b ← hero_hook.applies count
  if b
  then
    if filled = 0#usize
    then ok none
    else
      let turn ← count / hero_hook.HOOK_EVERY
      let i ← lift (UScalar.cast .U64 filled)
      let i1 ← turn % i
      let index ← lift (UScalar.cast .Usize i1)
      ok (some index)
  else ok none

/-- [timeways_rules::prompts::PROMPTS_KEPT]
    Source: 'crates/rules/src/prompts.rs', lines 5:0-5:34
    Visibility: public -/
@[global_simps, irreducible] def prompts.PROMPTS_KEPT : Std.U64 := 500#u64

/-- [timeways_rules::prompts::oldest_prompt_kept]:
    Source: 'crates/rules/src/prompts.rs', lines 10:0-12:1
    Visibility: public -/
def prompts.oldest_prompt_kept (newest : Std.U64) : Result Std.U64 := do
  let i ← prompts.PROMPTS_KEPT - 1#u64
  ok (core.num.U64.saturating_sub newest i)

/-- [timeways_rules::quest_log::DAY_SECONDS]
    Source: 'crates/rules/src/quest_log.rs', lines 6:0-6:39
    Visibility: public -/
@[global_simps, irreducible]
def quest_log.DAY_SECONDS : Result Std.U64 := 24#u64 * 3600#u64

/-- [timeways_rules::quest_log::MIN_SET_STEPS]
    Source: 'crates/rules/src/quest_log.rs', lines 9:0-9:35
    Visibility: public -/
@[global_simps, irreducible] def quest_log.MIN_SET_STEPS : Std.Usize := 2#usize

/-- [timeways_rules::quest_log::MAX_SET_STEPS]
    Source: 'crates/rules/src/quest_log.rs', lines 10:0-10:35
    Visibility: public -/
@[global_simps, irreducible] def quest_log.MAX_SET_STEPS : Std.Usize := 3#usize

/-- [timeways_rules::quest_log::{impl core::clone::Clone for timeways_rules::quest_log::Goal}::clone]:
    Source: 'crates/rules/src/quest_log.rs', lines 13:9-13:14
    Visibility: public -/
def quest_log.Goal.Insts.CoreCloneClone.clone
  (self : quest_log.Goal) : Result quest_log.Goal := do
  ok self

/-- Trait implementation: [timeways_rules::quest_log::{impl core::clone::Clone for timeways_rules::quest_log::Goal}]
    Source: 'crates/rules/src/quest_log.rs', lines 13:9-13:14 -/
@[reducible]
def quest_log.Goal.Insts.CoreCloneClone : core.clone.Clone quest_log.Goal := {
  clone := quest_log.Goal.Insts.CoreCloneClone.clone
}

/-- [timeways_rules::quest_log::{timeways_rules::quest_log::Span}::contains]:
    Source: 'crates/rules/src/quest_log.rs', lines 29:4-31:5
    Visibility: public -/
def quest_log.Span.contains
  (self : quest_log.Span) (step : Std.Usize) : Result Bool := do
  if self.first <= step
  then ok (step <= self.last)
  else ok false

/-- [timeways_rules::quest_log::{impl core::cmp::PartialEq<timeways_rules::quest_log::Status> for timeways_rules::quest_log::Status}::eq]:
    Source: 'crates/rules/src/quest_log.rs', lines 63:22-63:31
    Visibility: public -/
def quest_log.Status.Insts.CoreCmpPartialEqStatus.eq
  (self : quest_log.Status) (other : quest_log.Status) : Result Bool := do
  let self1 := read_discriminant self
  let other1 := read_discriminant other
  ok (self1 = other1)

/-- [timeways_rules::quest_log::holds_wait]: loop 0:
    Source: 'crates/rules/src/quest_log.rs', lines 257:4-264:1 -/
@[rust_loop]
def quest_log.holds_wait_loop
  (steps : Slice quest_log.Goal) (i : Std.Usize) (step : Std.Usize) :
  Result Bool
  := do
  if step <= i
  then
    let g ← Slice.index_usize steps step
    match g with
    | quest_log.Goal.Wait _ => ok true
    | quest_log.Goal.Kill _ =>
      let step1 ← step + 1#usize
      quest_log.holds_wait_loop steps i step1
    | quest_log.Goal.Other =>
      let step1 ← step + 1#usize
      quest_log.holds_wait_loop steps i step1
  else ok false
partial_fixpoint

/-- [timeways_rules::quest_log::holds_wait]:
    Source: 'crates/rules/src/quest_log.rs', lines 255:0-264:1 -/
@[reducible]
def quest_log.holds_wait
  (steps : Slice quest_log.Goal) (span : quest_log.Span) : Result Bool := do
  quest_log.holds_wait_loop steps span.last span.first

/-- [timeways_rules::quest_log::fits]:
    Source: 'crates/rules/src/quest_log.rs', lines 245:0-252:1 -/
def quest_log.fits
  (span : quest_log.Span) (steps : Slice quest_log.Goal) : Result Bool := do
  let fits_steps ←
    if span.first < span.last
    then let i := Slice.len steps
         ok (span.last < i)
    else ok false
  if fits_steps
  then
    let i ← span.last - span.first
    let size ← i + 1#usize
    if quest_log.MIN_SET_STEPS <= size
    then
      if size <= quest_log.MAX_SET_STEPS
      then let b ← quest_log.holds_wait steps span
           ok (¬ b)
      else ok false
    else ok false
  else ok false

/-- [timeways_rules::quest_log::{timeways_rules::quest_log::Progress}::offered]:
    Source: 'crates/rules/src/quest_log.rs', lines 98:4-112:5 -/
def quest_log.Progress.offered
  (steps : Slice quest_log.Goal) (any_order : Option quest_log.Span) :
  Result quest_log.Progress
  := do
  let fitting ←
    match any_order with
    | none => ok none
    | some span =>
      do
      let b ← quest_log.fits span steps
      if b
      then ok any_order
      else ok none
  let v ← alloc.slice.Slice.to_vec quest_log.Goal.Insts.CoreCloneClone steps
  let i := Slice.len steps
  let v1 ←
    alloc.vec.from_elem (core.option.Option.Insts.CoreCloneClone
      core.clone.CloneU64) none i
  let i1 := Slice.len steps
  let v2 ← alloc.vec.from_elem core.clone.CloneU8 0#u8 i1
  ok
    {
      steps := v,
      any_order := fitting,
      status := quest_log.Status.Offered,
      accepted_at := none,
      done_times := v1,
      kills := v2,
      done_at := none
    }

/-- [timeways_rules::quest_log::{timeways_rules::quest_log::Progress}::steps_done]: loop 0:
    Source: 'crates/rules/src/quest_log.rs', lines 119:8-124:9
    Visibility: public -/
@[rust_loop]
def quest_log.Progress.steps_done_loop
  (self : quest_log.Progress) (count : Std.Usize) (step : Std.Usize) :
  Result Std.Usize
  := do
  let i := alloc.vec.Vec.len self.done_times
  if step < i
  then
    let o ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice (Option
        Std.U64)) self.done_times step
    let b := core.option.Option.is_some o
    let count1 ← if b
                   then count + 1#usize
                   else ok count
    let step1 ← step + 1#usize
    quest_log.Progress.steps_done_loop self count1 step1
  else ok count
partial_fixpoint

/-- [timeways_rules::quest_log::{timeways_rules::quest_log::Progress}::steps_done]:
    Source: 'crates/rules/src/quest_log.rs', lines 116:4-126:5
    Visibility: public -/
@[reducible]
def quest_log.Progress.steps_done
  (self : quest_log.Progress) : Result Std.Usize := do
  quest_log.Progress.steps_done_loop self 0#usize 0#usize

/-- [timeways_rules::quest_log::{timeways_rules::quest_log::Progress}::is_done]:
    Source: 'crates/rules/src/quest_log.rs', lines 129:4-131:5
    Visibility: public -/
def quest_log.Progress.is_done
  (self : quest_log.Progress) (step : Std.Usize) : Result Bool := do
  let i := alloc.vec.Vec.len self.done_times
  if step < i
  then
    let o ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice (Option
        Std.U64)) self.done_times step
    ok (core.option.Option.is_some o)
  else ok false

/-- [timeways_rules::quest_log::{timeways_rules::quest_log::Progress}::stage_start]:
    Source: 'crates/rules/src/quest_log.rs', lines 136:4-141:5
    Visibility: public -/
def quest_log.Progress.stage_start
  (self : quest_log.Progress) (step : Std.Usize) : Result Std.Usize := do
  match self.any_order with
  | none => ok step
  | some span =>
    let b ← quest_log.Span.contains span step
    if b
    then ok span.first
    else ok step

/-- [timeways_rules::quest_log::{timeways_rules::quest_log::Progress}::all_done_before]: loop 0:
    Source: 'crates/rules/src/quest_log.rs', lines 163:8-170:5 -/
@[rust_loop]
def quest_log.Progress.all_done_before_loop
  (self : quest_log.Progress) («end» : Std.Usize) (step : Std.Usize) :
  Result Bool
  := do
  if step < «end»
  then
    let b ← quest_log.Progress.is_done self step
    if b
    then
      let step1 ← step + 1#usize
      quest_log.Progress.all_done_before_loop self «end» step1
    else ok false
  else ok true
partial_fixpoint

/-- [timeways_rules::quest_log::{timeways_rules::quest_log::Progress}::all_done_before]:
    Source: 'crates/rules/src/quest_log.rs', lines 161:4-170:5 -/
@[reducible]
def quest_log.Progress.all_done_before
  (self : quest_log.Progress) («end» : Std.Usize) : Result Bool := do
  quest_log.Progress.all_done_before_loop self «end» 0#usize

/-- [timeways_rules::quest_log::{timeways_rules::quest_log::Progress}::is_open]:
    Source: 'crates/rules/src/quest_log.rs', lines 153:4-158:5
    Visibility: public -/
def quest_log.Progress.is_open
  (self : quest_log.Progress) (step : Std.Usize) : Result Bool := do
  let b ←
    quest_log.Status.Insts.CoreCmpPartialEqStatus.eq self.status
      quest_log.Status.Accepted
  if b
  then
    let i := alloc.vec.Vec.len self.steps
    if step < i
    then
      let b1 ← quest_log.Progress.is_done self step
      if b1
      then ok false
      else
        let i1 ← quest_log.Progress.stage_start self step
        quest_log.Progress.all_done_before self i1
    else ok false
  else ok false

/-- [timeways_rules::quest_log::later]:
    Source: 'crates/rules/src/quest_log.rs', lines 266:0-272:1 -/
def quest_log.later
  (latest : Option Std.U64) («at» : Option Std.U64) :
  Result (Option Std.U64)
  := do
  match latest with
  | none => ok «at»
  | some old =>
    match «at» with
    | none => ok latest
    | some new => if new > old
                  then ok «at»
                  else ok latest

/-- [timeways_rules::quest_log::{timeways_rules::quest_log::Progress}::last_done_before]: loop 0:
    Source: 'crates/rules/src/quest_log.rs', lines 190:8-193:9 -/
@[rust_loop]
def quest_log.Progress.last_done_before_loop
  (self : quest_log.Progress) («end» : Std.Usize) (latest : Option Std.U64)
  (step : Std.Usize) :
  Result (Option Std.U64)
  := do
  if step < «end»
  then
    let i := alloc.vec.Vec.len self.done_times
    if step < i
    then
      let o ←
        alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice (Option
          Std.U64)) self.done_times step
      let latest1 ← quest_log.later latest o
      let step1 ← step + 1#usize
      quest_log.Progress.last_done_before_loop self «end» latest1 step1
    else ok latest
  else ok latest
partial_fixpoint

/-- [timeways_rules::quest_log::{timeways_rules::quest_log::Progress}::last_done_before]:
    Source: 'crates/rules/src/quest_log.rs', lines 187:4-195:5 -/
@[reducible]
def quest_log.Progress.last_done_before
  (self : quest_log.Progress) («end» : Std.Usize) :
  Result (Option Std.U64)
  := do
  quest_log.Progress.last_done_before_loop self «end» none 0#usize

/-- [timeways_rules::quest_log::{timeways_rules::quest_log::Progress}::opened_at]:
    Source: 'crates/rules/src/quest_log.rs', lines 175:4-183:5
    Visibility: public -/
def quest_log.Progress.opened_at
  (self : quest_log.Progress) (step : Std.Usize) :
  Result (Option Std.U64)
  := do
  let b ← quest_log.Progress.is_open self step
  if b
  then
    let i ← quest_log.Progress.stage_start self step
    let o ← quest_log.Progress.last_done_before self i
    match o with
    | none => ok self.accepted_at
    | some _ => ok o
  else ok none

/-- [timeways_rules::quest_log::{timeways_rules::quest_log::Progress}::ready_at]:
    Source: 'crates/rules/src/quest_log.rs', lines 199:4-211:5
    Visibility: public -/
def quest_log.Progress.ready_at
  (self : quest_log.Progress) (step : Std.Usize) :
  Result (Option Std.U64)
  := do
  let i := alloc.vec.Vec.len self.steps
  if step >= i
  then ok none
  else
    let g ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice
        quest_log.Goal) self.steps step
    match g with
    | quest_log.Goal.Wait days =>
      let o ← quest_log.Progress.opened_at self step
      match o with
      | none => ok none
      | some opened =>
        let i1 ← lift (core.convert.num.FromU64U8.from days)
        let i2 ← quest_log.DAY_SECONDS
        let i3 ← i1 * i2
        let i4 ← lift (core.num.U64.saturating_add opened i3)
        ok (some i4)
    | quest_log.Goal.Kill _ => ok none
    | quest_log.Goal.Other => ok none

/-- [timeways_rules::quest_log::{timeways_rules::quest_log::Progress}::finish_step]:
    Source: 'crates/rules/src/quest_log.rs', lines 215:4-228:5 -/
def quest_log.Progress.finish_step
  (self : quest_log.Progress) (step : Std.Usize) («at» : Std.U64) :
  Result quest_log.Progress
  := do
  let o ← quest_log.Progress.ready_at self step
  let early ←
    match o with
    | none => ok false
    | some ready => ok («at» < ready)
  let b ← quest_log.Progress.is_open self step
  if b
  then
    if early
    then ok self
    else
      let (_, index_mut_back) ←
        alloc.vec.Vec.index_mut (core.slice.index.SliceIndexUsizeSlice (Option
          Std.U64)) self.done_times step
      let v := index_mut_back (some «at»)
      let i ← quest_log.Progress.steps_done { self with done_times := v }
      let i1 := alloc.vec.Vec.len self.steps
      if i = i1
      then
        ok
          {
            self
              with
              status := quest_log.Status.Done,
              done_times := v,
              done_at := (some «at»)
          }
      else ok { self with done_times := v }
  else ok self

/-- [timeways_rules::quest_log::{timeways_rules::quest_log::Progress}::count_kill]:
    Source: 'crates/rules/src/quest_log.rs', lines 231:4-241:5 -/
def quest_log.Progress.count_kill
  (self : quest_log.Progress) (step : Std.Usize) :
  Result quest_log.Progress
  := do
  let i := alloc.vec.Vec.len self.steps
  if step >= i
  then ok self
  else
    let g ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice
        quest_log.Goal) self.steps step
    match g with
    | quest_log.Goal.Wait _ => ok self
    | quest_log.Goal.Kill count =>
      let b ← quest_log.Progress.is_open self step
      if b
      then
        let i1 ←
          alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice Std.U8)
            self.kills step
        if i1 < count
        then
          let (i2, index_mut_back) ←
            alloc.vec.Vec.index_mut (core.slice.index.SliceIndexUsizeSlice
              Std.U8) self.kills step
          let i3 ← i2 + 1#u8
          let v := index_mut_back i3
          ok { self with kills := v }
        else ok self
      else ok self
    | quest_log.Goal.Other => ok self

/-- [timeways_rules::quest_log::abandon]: loop 0:
    Source: 'crates/rules/src/quest_log.rs', lines 377:4-387:1 -/
@[rust_loop]
def quest_log.abandon_loop
  (quests : Slice quest_log.Quest) (number : Std.U64) (index : Std.Usize) :
  Result (Slice quest_log.Quest)
  := do
  let i := Slice.len quests
  if index < i
  then
    let (quest, index_mut_back) ← Slice.index_mut_usize quests index
    let b ←
      quest_log.Status.Insts.CoreCmpPartialEqStatus.eq quest.progress.status
        quest_log.Status.Offered
    let «open» ←
      if b
      then ok true
      else
        quest_log.Status.Insts.CoreCmpPartialEqStatus.eq quest.progress.status
          quest_log.Status.Accepted
    if quest.number = number
    then
      if «open»
      then
        ok (index_mut_back
          {
            quest
              with
              progress :=
                { quest.progress with status := quest_log.Status.Abandoned }
          })
      else
        let index1 ← index + 1#usize
        let s := index_mut_back quest
        quest_log.abandon_loop s number index1
    else
      let index1 ← index + 1#usize
      let s := index_mut_back quest
      quest_log.abandon_loop s number index1
  else ok quests
partial_fixpoint

/-- [timeways_rules::quest_log::abandon]:
    Source: 'crates/rules/src/quest_log.rs', lines 375:0-387:1 -/
@[reducible]
def quest_log.abandon
  (quests : Slice quest_log.Quest) (number : Std.U64) :
  Result (Slice quest_log.Quest)
  := do
  quest_log.abandon_loop quests number 0#usize

/-- [timeways_rules::quest_log::waiting_offer]: loop 0:
    Source: 'crates/rules/src/quest_log.rs', lines 363:4-369:5 -/
@[rust_loop]
def quest_log.waiting_offer_loop
  (quests : Slice quest_log.Quest) (number : Std.U64) (index : Std.Usize) :
  Result (Option Std.Usize)
  := do
  let i := Slice.len quests
  if index < i
  then
    let quest ← Slice.index_usize quests index
    if quest.number = number
    then
      let b ←
        quest_log.Status.Insts.CoreCmpPartialEqStatus.eq quest.progress.status
          quest_log.Status.Offered
      if b
      then ok (some index)
      else
        let index1 ← index + 1#usize
        quest_log.waiting_offer_loop quests number index1
    else
      let index1 ← index + 1#usize
      quest_log.waiting_offer_loop quests number index1
  else ok none
partial_fixpoint

/-- [timeways_rules::quest_log::waiting_offer]:
    Source: 'crates/rules/src/quest_log.rs', lines 361:0-371:1 -/
@[reducible]
def quest_log.waiting_offer
  (quests : Slice quest_log.Quest) (number : Std.U64) :
  Result (Option Std.Usize)
  := do
  quest_log.waiting_offer_loop quests number 0#usize

/-- [timeways_rules::quest_log::find]: loop 0:
    Source: 'crates/rules/src/quest_log.rs', lines 350:4-357:1 -/
@[rust_loop]
def quest_log.find_loop
  (quests : Slice quest_log.Quest) (number : Std.U64) (index : Std.Usize) :
  Result (Option Std.Usize)
  := do
  let i := Slice.len quests
  if index < i
  then
    let q ← Slice.index_usize quests index
    if q.number = number
    then ok (some index)
    else
      let index1 ← index + 1#usize
      quest_log.find_loop quests number index1
  else ok none
partial_fixpoint

/-- [timeways_rules::quest_log::find]:
    Source: 'crates/rules/src/quest_log.rs', lines 348:0-357:1 -/
@[reducible]
def quest_log.find
  (quests : Slice quest_log.Quest) (number : Std.U64) :
  Result (Option Std.Usize)
  := do
  quest_log.find_loop quests number 0#usize

/-- [timeways_rules::quest_log::decline_waiting_offers_of]: loop 0:
    Source: 'crates/rules/src/quest_log.rs', lines 337:4-343:5 -/
@[rust_loop]
def quest_log.decline_waiting_offers_of_loop
  (quests : Slice quest_log.Quest) (giver : String) (index : Std.Usize) :
  Result (Slice quest_log.Quest)
  := do
  let i := Slice.len quests
  if index < i
  then
    let (quest, index_mut_back) ← Slice.index_mut_usize quests index
    let b ←
      quest_log.Status.Insts.CoreCmpPartialEqStatus.eq quest.progress.status
        quest_log.Status.Offered
    let s ←
      if b
      then
        do
        let b1 ←
          alloc.string.String.Insts.CoreCmpPartialEqString.eq quest.giver giver
        if b1
        then ok quest_log.Status.Declined
        else ok quest.progress.status
      else ok quest.progress.status
    let index1 ← index + 1#usize
    let s1 :=
      index_mut_back
        { quest with progress := { quest.progress with status := s } }
    quest_log.decline_waiting_offers_of_loop s1 giver index1
  else ok quests
partial_fixpoint

/-- [timeways_rules::quest_log::decline_waiting_offers_of]:
    Source: 'crates/rules/src/quest_log.rs', lines 335:0-344:1 -/
@[reducible]
def quest_log.decline_waiting_offers_of
  (quests : Slice quest_log.Quest) (giver : String) :
  Result (Slice quest_log.Quest)
  := do
  quest_log.decline_waiting_offers_of_loop quests giver 0#usize

/-- [timeways_rules::quest_log::apply]:
    Source: 'crates/rules/src/quest_log.rs', lines 289:0-328:1 -/
def quest_log.apply
  (quests : alloc.vec.Vec quest_log.Quest) (change : quest_log.Change)
  (line : Std.Usize) :
  Result (alloc.vec.Vec quest_log.Quest)
  := do
  match change with
  | quest_log.Change.Offered number giver steps any_order =>
    let (s, deref_mut_back) ← lift (alloc.vec.Vec.deref_mut quests)
    let s1 ← quest_log.decline_waiting_offers_of s giver
    let quests1 := deref_mut_back s1
    let s2 ← alloc.string.String.Insts.CoreCloneClone.clone giver
    let s3 := alloc.vec.Vec.deref steps
    let p ← quest_log.Progress.offered s3 any_order
    alloc.vec.Vec.push quests1 ({ line, number, giver := s2, progress := p } :
      quest_log.Quest)
  | quest_log.Change.Accepted number «at» =>
    let s := alloc.vec.Vec.deref quests
    let o ← quest_log.waiting_offer s number
    match o with
    | none => ok quests
    | some index =>
      let (q, index_mut_back) ←
        alloc.vec.Vec.index_mut (core.slice.index.SliceIndexUsizeSlice
          quest_log.Quest) quests index
      let quests1 :=
        index_mut_back
          {
            q
              with
              progress :=
                { q.progress with status := quest_log.Status.Accepted }
          }
      let (q1, index_mut_back1) ←
        alloc.vec.Vec.index_mut (core.slice.index.SliceIndexUsizeSlice
          quest_log.Quest) quests1 index
      ok (index_mut_back1
        { q1 with progress := { q1.progress with accepted_at := (some «at») }
        })
  | quest_log.Change.Declined number =>
    let s := alloc.vec.Vec.deref quests
    let o ← quest_log.waiting_offer s number
    match o with
    | none => ok quests
    | some index =>
      let (q, index_mut_back) ←
        alloc.vec.Vec.index_mut (core.slice.index.SliceIndexUsizeSlice
          quest_log.Quest) quests index
      ok (index_mut_back
        {
          q
            with
            progress := { q.progress with status := quest_log.Status.Declined }
        })
  | quest_log.Change.StepDone number step «at» =>
    let s := alloc.vec.Vec.deref quests
    let o ← quest_log.find s number
    match o with
    | none => ok quests
    | some index =>
      let (q, index_mut_back) ←
        alloc.vec.Vec.index_mut (core.slice.index.SliceIndexUsizeSlice
          quest_log.Quest) quests index
      let p ← quest_log.Progress.finish_step q.progress step «at»
      ok (index_mut_back { q with progress := p })
  | quest_log.Change.Killed number step =>
    let s := alloc.vec.Vec.deref quests
    let o ← quest_log.find s number
    match o with
    | none => ok quests
    | some index =>
      let (q, index_mut_back) ←
        alloc.vec.Vec.index_mut (core.slice.index.SliceIndexUsizeSlice
          quest_log.Quest) quests index
      let p ← quest_log.Progress.count_kill q.progress step
      ok (index_mut_back { q with progress := p })
  | quest_log.Change.Abandoned number =>
    let (s, deref_mut_back) ← lift (alloc.vec.Vec.deref_mut quests)
    let s1 ← quest_log.abandon s number
    ok (deref_mut_back s1)

/-- [timeways_rules::quest_log::quest_log]: loop 0:
    Source: 'crates/rules/src/quest_log.rs', lines 282:4-285:5
    Visibility: public -/
@[rust_loop]
def quest_log.quest_log_loop
  (changes : Slice quest_log.Change) (quests : alloc.vec.Vec quest_log.Quest)
  (line : Std.Usize) :
  Result (alloc.vec.Vec quest_log.Quest)
  := do
  let i := Slice.len changes
  if line < i
  then
    let c ← Slice.index_usize changes line
    let quests1 ← quest_log.apply quests c line
    let line1 ← line + 1#usize
    quest_log.quest_log_loop changes quests1 line1
  else ok quests
partial_fixpoint

/-- [timeways_rules::quest_log::quest_log]:
    Source: 'crates/rules/src/quest_log.rs', lines 279:0-287:1
    Visibility: public -/
@[reducible]
def quest_log.quest_log
  (changes : Slice quest_log.Change) :
  Result (alloc.vec.Vec quest_log.Quest)
  := do
  quest_log.quest_log_loop changes (alloc.vec.Vec.new quest_log.Quest) 0#usize

/-- [timeways_rules::story_shelf::is_taken]: loop 0:
    Source: 'crates/rules/src/story_shelf.rs', lines 18:4-29:1
    Visibility: public -/
@[rust_loop]
def story_shelf.is_taken_loop
  (lines : Slice story_shelf.ShelfLine) (number : Std.U64) (index : Std.Usize)
  :
  Result Bool
  := do
  let i := Slice.len lines
  if index < i
  then
    let line ← Slice.index_usize lines index
    match line with
    | story_shelf.ShelfLine.Accepted n =>
      if n = number
      then ok true
      else
        let index1 ← index + 1#usize
        story_shelf.is_taken_loop lines number index1
    | story_shelf.ShelfLine.Removed _ =>
      let index1 ← index + 1#usize
      story_shelf.is_taken_loop lines number index1
  else ok false
partial_fixpoint

/-- [timeways_rules::story_shelf::is_taken]:
    Source: 'crates/rules/src/story_shelf.rs', lines 16:0-29:1
    Visibility: public -/
@[reducible]
def story_shelf.is_taken
  (lines : Slice story_shelf.ShelfLine) (number : Std.U64) : Result Bool := do
  story_shelf.is_taken_loop lines number 0#usize

/-- [timeways_rules::story_shelf::is_removed]: loop 0:
    Source: 'crates/rules/src/story_shelf.rs', lines 35:4-45:1
    Visibility: public -/
@[rust_loop]
def story_shelf.is_removed_loop
  (lines : Slice story_shelf.ShelfLine) (number : Std.U64) (index : Std.Usize)
  :
  Result Bool
  := do
  let i := Slice.len lines
  if index < i
  then
    let line ← Slice.index_usize lines index
    match line with
    | story_shelf.ShelfLine.Accepted _ =>
      let index1 ← index + 1#usize
      story_shelf.is_removed_loop lines number index1
    | story_shelf.ShelfLine.Removed n =>
      if n = number
      then ok true
      else
        let index1 ← index + 1#usize
        story_shelf.is_removed_loop lines number index1
  else ok false
partial_fixpoint

/-- [timeways_rules::story_shelf::is_removed]:
    Source: 'crates/rules/src/story_shelf.rs', lines 33:0-45:1
    Visibility: public -/
@[reducible]
def story_shelf.is_removed
  (lines : Slice story_shelf.ShelfLine) (number : Std.U64) : Result Bool := do
  story_shelf.is_removed_loop lines number 0#usize

/-- [timeways_rules::story_shelf::holds]: loop 0:
    Source: 'crates/rules/src/story_shelf.rs', lines 50:4-57:1 -/
@[rust_loop]
def story_shelf.holds_loop
  (numbers : Slice Std.U64) (number : Std.U64) (index : Std.Usize) :
  Result Bool
  := do
  let i := Slice.len numbers
  if index < i
  then
    let i1 ← Slice.index_usize numbers index
    if i1 = number
    then ok true
    else
      let index1 ← index + 1#usize
      story_shelf.holds_loop numbers number index1
  else ok false
partial_fixpoint

/-- [timeways_rules::story_shelf::holds]:
    Source: 'crates/rules/src/story_shelf.rs', lines 48:0-57:1 -/
@[reducible]
def story_shelf.holds
  (numbers : Slice Std.U64) (number : Std.U64) : Result Bool := do
  story_shelf.holds_loop numbers number 0#usize

/-- [timeways_rules::story_shelf::lands]:
    Source: 'crates/rules/src/story_shelf.rs', lines 63:0-70:1
    Visibility: public -/
def story_shelf.lands
  (lines : Slice story_shelf.ShelfLine) (line : story_shelf.ShelfLine)
  (used : Slice Std.U64) :
  Result Bool
  := do
  match line with
  | story_shelf.ShelfLine.Accepted number =>
    let b ← story_shelf.is_taken lines number
    ok (¬ b)
  | story_shelf.ShelfLine.Removed number =>
    let b ← story_shelf.is_taken lines number
    if b
    then
      let b1 ← story_shelf.is_removed lines number
      if b1
      then ok false
      else let b2 ← story_shelf.holds used number
           ok (¬ b2)
    else ok false

/-- [timeways_rules::story_shelf::standing]: loop 0:
    Source: 'crates/rules/src/story_shelf.rs', lines 78:4-86:5
    Visibility: public -/
@[rust_loop]
def story_shelf.standing_loop
  (lines : Slice story_shelf.ShelfLine) (numbers : alloc.vec.Vec Std.U64)
  (index : Std.Usize) :
  Result (alloc.vec.Vec Std.U64)
  := do
  let i := Slice.len lines
  if index < i
  then
    let line ← Slice.index_usize lines index
    let numbers1 ←
      match line with
      | story_shelf.ShelfLine.Accepted number =>
        do
        let b ← story_shelf.is_removed lines number
        if b
        then ok numbers
        else alloc.vec.Vec.push numbers number
      | story_shelf.ShelfLine.Removed _ => ok numbers
    let index1 ← index + 1#usize
    story_shelf.standing_loop lines numbers1 index1
  else ok numbers
partial_fixpoint

/-- [timeways_rules::story_shelf::standing]:
    Source: 'crates/rules/src/story_shelf.rs', lines 75:0-88:1
    Visibility: public -/
@[reducible]
def story_shelf.standing
  (lines : Slice story_shelf.ShelfLine) : Result (alloc.vec.Vec Std.U64) := do
  story_shelf.standing_loop lines (alloc.vec.Vec.new Std.U64) 0#usize

/-- [timeways_rules::trust::MIN_TRUST]
    Source: 'crates/rules/src/trust.rs', lines 4:0-4:32
    Visibility: public -/
@[global_simps, irreducible] def trust.MIN_TRUST : Std.I64 := (-100)#i64

/-- [timeways_rules::trust::MAX_TRUST]
    Source: 'crates/rules/src/trust.rs', lines 5:0-5:31
    Visibility: public -/
@[global_simps, irreducible] def trust.MAX_TRUST : Std.I64 := 100#i64

/-- [timeways_rules::trust::next_trust]:
    Source: 'crates/rules/src/trust.rs', lines 10:0-14:1
    Visibility: public -/
def trust.next_trust
  (held : Option Std.I64) («by» : Std.I64) : Result Std.I64 := do
  let i ← lift (core.option.Option.unwrap_or held 0#i64)
  let i1 ← lift (core.num.I64.saturating_add i «by»)
  core.cmp.impls.OrdI64.clamp i1 trust.MIN_TRUST trust.MAX_TRUST

end timeways_rules
