-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [timeways_rules]: function definitions
module
public import Aeneas
public import Timeways.Types
public import Timeways.FunsExternal
@[expose] public section
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace timeways_rules

/-- Trait implementation: [core::option::{impl core::clone::Clone for core::option::Option<T>}]
    Source: '/rustc/library/core/src/option.rs', lines 2271:0-2275:40
    Name pattern: [core::clone::Clone<core::option::Option<@T>>] -/
@[reducible, rust_trait_impl "core::clone::Clone<core::option::Option<@T>>"]
def core.option.Option.Insts.CoreCloneClone {T : Type} (cloneCloneInst :
  core.clone.Clone T) : core.clone.Clone (Option T) := {
  clone := core.option.Option.Insts.CoreCloneClone.clone cloneCloneInst
}

/-- [timeways_rules::budget::HOUR]
    Source: 'crates/rules/src/budget.rs', lines 5:0-5:23 -/
@[global_simps, irreducible] def budget.HOUR : Std.U64 := 3600#u64

/-- [timeways_rules::budget::{timeways_rules::budget::Budget}::take]:
    Source: 'crates/rules/src/budget.rs', lines 17:4-30:5
    Visibility: public -/
def budget.Budget.take
  (self : budget.Budget) («at» : Std.U64) :
  Result (Bool × budget.Budget)
  := do
  let oldest ← Array.index_usize self.spoken 0#usize
  let too_soon ←
    match oldest with
    | none => ok false
    | some oldest1 =>
      do
      let i ← lift (core.num.U64.saturating_sub «at» oldest1)
      ok (i < budget.HOUR)
  if too_soon
  then ok (false, self)
  else
    let o ← Array.index_usize self.spoken 1#usize
    let o1 ← Array.index_usize self.spoken 2#usize
    ok (true, { spoken := (Array.make 3#usize [ o, o1, some «at» ]) })

/-- [timeways_rules::hero_hook::HOOK_EVERY]
    Source: 'crates/rules/src/hero_hook.rs', lines 4:0-4:30
    Visibility: public -/
@[global_simps, irreducible] def hero_hook.HOOK_EVERY : Std.U64 := 3#u64

/-- [timeways_rules::hero_hook::applies]:
    Source: 'crates/rules/src/hero_hook.rs', lines 10:0-12:1
    Visibility: public -/
def hero_hook.applies (count : Std.U64) : Result Bool := do
  let i ← count % hero_hook.HOOK_EVERY
  let i1 ← hero_hook.HOOK_EVERY - 1#u64
  ok (i = i1)

/-- [timeways_rules::hero_hook::pick]:
    Source: 'crates/rules/src/hero_hook.rs', lines 18:0-29:1
    Visibility: public -/
def hero_hook.pick
  (filled : Std.Usize) (count : Std.U64) : Result (Option Std.Usize) := do
  let b ← hero_hook.applies count
  if b
  then
    if filled = 0#usize
    then ok none
    else
      let turn ← count / hero_hook.HOOK_EVERY
      let i ← lift (UScalar.cast .U64 filled)
      let i1 ← turn % i
      let index ← lift (UScalar.cast .Usize i1)
      ok (some index)
  else ok none

/-- [timeways_rules::prompts::PROMPTS_KEPT]
    Source: 'crates/rules/src/prompts.rs', lines 5:0-5:34
    Visibility: public -/
@[global_simps, irreducible] def prompts.PROMPTS_KEPT : Std.U64 := 500#u64

/-- [timeways_rules::prompts::oldest_prompt_kept]:
    Source: 'crates/rules/src/prompts.rs', lines 10:0-12:1
    Visibility: public -/
def prompts.oldest_prompt_kept (newest : Std.U64) : Result Std.U64 := do
  let i ← prompts.PROMPTS_KEPT - 1#u64
  ok (core.num.U64.saturating_sub newest i)

/-- [timeways_rules::quest_log::DAY_SECONDS]
    Source: 'crates/rules/src/quest_log.rs', lines 6:0-6:39
    Visibility: public -/
@[global_simps, irreducible]
def quest_log.DAY_SECONDS : Result Std.U64 := 24#u64 * 3600#u64

/-- [timeways_rules::quest_log::MIN_SET_STEPS]
    Source: 'crates/rules/src/quest_log.rs', lines 9:0-9:35
    Visibility: public -/
@[global_simps, irreducible] def quest_log.MIN_SET_STEPS : Std.Usize := 2#usize

/-- [timeways_rules::quest_log::MAX_SET_STEPS]
    Source: 'crates/rules/src/quest_log.rs', lines 10:0-10:35
    Visibility: public -/
@[global_simps, irreducible] def quest_log.MAX_SET_STEPS : Std.Usize := 3#usize

/-- [timeways_rules::quest_log::{impl core::clone::Clone for timeways_rules::quest_log::Goal}::clone]:
    Source: 'crates/rules/src/quest_log.rs', lines 13:9-13:14
    Visibility: public -/
def quest_log.Goal.Insts.CoreCloneClone.clone
  (self : quest_log.Goal) : Result quest_log.Goal := do
  ok self

/-- Trait implementation: [timeways_rules::quest_log::{impl core::clone::Clone for timeways_rules::quest_log::Goal}]
    Source: 'crates/rules/src/quest_log.rs', lines 13:9-13:14 -/
@[reducible]
def quest_log.Goal.Insts.CoreCloneClone : core.clone.Clone quest_log.Goal := {
  clone := quest_log.Goal.Insts.CoreCloneClone.clone
}

/-- [timeways_rules::quest_log::{timeways_rules::quest_log::Span}::contains]:
    Source: 'crates/rules/src/quest_log.rs', lines 29:4-31:5
    Visibility: public -/
def quest_log.Span.contains
  (self : quest_log.Span) (step : Std.Usize) : Result Bool := do
  if self.first <= step
  then ok (step <= self.last)
  else ok false

/-- [timeways_rules::quest_log::{impl core::cmp::PartialEq<timeways_rules::quest_log::Status> for timeways_rules::quest_log::Status}::eq]:
    Source: 'crates/rules/src/quest_log.rs', lines 63:22-63:31
    Visibility: public -/
def quest_log.Status.Insts.CoreCmpPartialEqStatus.eq
  (self : quest_log.Status) (other : quest_log.Status) : Result Bool := do
  let self1 := read_discriminant self
  let other1 := read_discriminant other
  ok (self1 = other1)

/-- [timeways_rules::quest_log::holds_wait]: loop 0:
    Source: 'crates/rules/src/quest_log.rs', lines 257:4-264:1 -/
@[rust_loop]
def quest_log.holds_wait_loop
  (steps : Slice quest_log.Goal) (i : Std.Usize) (step : Std.Usize) :
  Result Bool
  := do
  if step <= i
  then
    let g ← Slice.index_usize steps step
    match g with
    | quest_log.Goal.Wait _ => ok true
    | quest_log.Goal.Kill _ =>
      let step1 ← step + 1#usize
      quest_log.holds_wait_loop steps i step1
    | quest_log.Goal.Other =>
      let step1 ← step + 1#usize
      quest_log.holds_wait_loop steps i step1
  else ok false
partial_fixpoint

/-- [timeways_rules::quest_log::holds_wait]:
    Source: 'crates/rules/src/quest_log.rs', lines 255:0-264:1 -/
@[reducible]
def quest_log.holds_wait
  (steps : Slice quest_log.Goal) (span : quest_log.Span) : Result Bool := do
  quest_log.holds_wait_loop steps span.last span.first

/-- [timeways_rules::quest_log::fits]:
    Source: 'crates/rules/src/quest_log.rs', lines 245:0-252:1 -/
def quest_log.fits
  (span : quest_log.Span) (steps : Slice quest_log.Goal) : Result Bool := do
  let fits_steps ←
    if span.first < span.last
    then let i := Slice.len steps
         ok (span.last < i)
    else ok false
  if fits_steps
  then
    let i ← span.last - span.first
    let size ← i + 1#usize
    if quest_log.MIN_SET_STEPS <= size
    then
      if size <= quest_log.MAX_SET_STEPS
      then let b ← quest_log.holds_wait steps span
           ok (¬ b)
      else ok false
    else ok false
  else ok false

/-- [timeways_rules::quest_log::{timeways_rules::quest_log::Progress}::offered]:
    Source: 'crates/rules/src/quest_log.rs', lines 98:4-112:5 -/
def quest_log.Progress.offered
  (steps : Slice quest_log.Goal) (any_order : Option quest_log.Span) :
  Result quest_log.Progress
  := do
  let fitting ←
    match any_order with
    | none => ok none
    | some span =>
      do
      let b ← quest_log.fits span steps
      if b
      then ok any_order
      else ok none
  let v ← alloc.slice.Slice.to_vec quest_log.Goal.Insts.CoreCloneClone steps
  let i := Slice.len steps
  let v1 ←
    alloc.vec.from_elem (core.option.Option.Insts.CoreCloneClone
      core.clone.CloneU64) none i
  let i1 := Slice.len steps
  let v2 ← alloc.vec.from_elem core.clone.CloneU8 0#u8 i1
  ok
    {
      steps := v,
      any_order := fitting,
      status := quest_log.Status.Offered,
      accepted_at := none,
      done_times := v1,
      kills := v2,
      done_at := none
    }

/-- [timeways_rules::quest_log::{timeways_rules::quest_log::Progress}::steps_done]: loop 0:
    Source: 'crates/rules/src/quest_log.rs', lines 119:8-124:9
    Visibility: public -/
@[rust_loop]
def quest_log.Progress.steps_done_loop
  (self : quest_log.Progress) (count : Std.Usize) (step : Std.Usize) :
  Result Std.Usize
  := do
  let i := alloc.vec.Vec.len self.done_times
  if step < i
  then
    let o ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice (Option
        Std.U64)) self.done_times step
    let b := core.option.Option.is_some o
    let count1 ← if b
                   then count + 1#usize
                   else ok count
    let step1 ← step + 1#usize
    quest_log.Progress.steps_done_loop self count1 step1
  else ok count
partial_fixpoint

/-- [timeways_rules::quest_log::{timeways_rules::quest_log::Progress}::steps_done]:
    Source: 'crates/rules/src/quest_log.rs', lines 116:4-126:5
    Visibility: public -/
@[reducible]
def quest_log.Progress.steps_done
  (self : quest_log.Progress) : Result Std.Usize := do
  quest_log.Progress.steps_done_loop self 0#usize 0#usize

/-- [timeways_rules::quest_log::{timeways_rules::quest_log::Progress}::is_done]:
    Source: 'crates/rules/src/quest_log.rs', lines 129:4-131:5
    Visibility: public -/
def quest_log.Progress.is_done
  (self : quest_log.Progress) (step : Std.Usize) : Result Bool := do
  let i := alloc.vec.Vec.len self.done_times
  if step < i
  then
    let o ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice (Option
        Std.U64)) self.done_times step
    ok (core.option.Option.is_some o)
  else ok false

/-- [timeways_rules::quest_log::{timeways_rules::quest_log::Progress}::stage_start]:
    Source: 'crates/rules/src/quest_log.rs', lines 136:4-141:5
    Visibility: public -/
def quest_log.Progress.stage_start
  (self : quest_log.Progress) (step : Std.Usize) : Result Std.Usize := do
  match self.any_order with
  | none => ok step
  | some span =>
    let b ← quest_log.Span.contains span step
    if b
    then ok span.first
    else ok step

/-- [timeways_rules::quest_log::{timeways_rules::quest_log::Progress}::all_done_before]: loop 0:
    Source: 'crates/rules/src/quest_log.rs', lines 163:8-170:5 -/
@[rust_loop]
def quest_log.Progress.all_done_before_loop
  (self : quest_log.Progress) («end» : Std.Usize) (step : Std.Usize) :
  Result Bool
  := do
  if step < «end»
  then
    let b ← quest_log.Progress.is_done self step
    if b
    then
      let step1 ← step + 1#usize
      quest_log.Progress.all_done_before_loop self «end» step1
    else ok false
  else ok true
partial_fixpoint

/-- [timeways_rules::quest_log::{timeways_rules::quest_log::Progress}::all_done_before]:
    Source: 'crates/rules/src/quest_log.rs', lines 161:4-170:5 -/
@[reducible]
def quest_log.Progress.all_done_before
  (self : quest_log.Progress) («end» : Std.Usize) : Result Bool := do
  quest_log.Progress.all_done_before_loop self «end» 0#usize

/-- [timeways_rules::quest_log::{timeways_rules::quest_log::Progress}::is_open]:
    Source: 'crates/rules/src/quest_log.rs', lines 153:4-158:5
    Visibility: public -/
def quest_log.Progress.is_open
  (self : quest_log.Progress) (step : Std.Usize) : Result Bool := do
  let b ←
    quest_log.Status.Insts.CoreCmpPartialEqStatus.eq self.status
      quest_log.Status.Accepted
  if b
  then
    let i := alloc.vec.Vec.len self.steps
    if step < i
    then
      let b1 ← quest_log.Progress.is_done self step
      if b1
      then ok false
      else
        let i1 ← quest_log.Progress.stage_start self step
        quest_log.Progress.all_done_before self i1
    else ok false
  else ok false

/-- [timeways_rules::quest_log::later]:
    Source: 'crates/rules/src/quest_log.rs', lines 266:0-272:1 -/
def quest_log.later
  (latest : Option Std.U64) («at» : Option Std.U64) :
  Result (Option Std.U64)
  := do
  match latest with
  | none => ok «at»
  | some old =>
    match «at» with
    | none => ok latest
    | some new => if new > old
                  then ok «at»
                  else ok latest

/-- [timeways_rules::quest_log::{timeways_rules::quest_log::Progress}::last_done_before]: loop 0:
    Source: 'crates/rules/src/quest_log.rs', lines 190:8-193:9 -/
@[rust_loop]
def quest_log.Progress.last_done_before_loop
  (self : quest_log.Progress) («end» : Std.Usize) (latest : Option Std.U64)
  (step : Std.Usize) :
  Result (Option Std.U64)
  := do
  if step < «end»
  then
    let i := alloc.vec.Vec.len self.done_times
    if step < i
    then
      let o ←
        alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice (Option
          Std.U64)) self.done_times step
      let latest1 ← quest_log.later latest o
      let step1 ← step + 1#usize
      quest_log.Progress.last_done_before_loop self «end» latest1 step1
    else ok latest
  else ok latest
partial_fixpoint

/-- [timeways_rules::quest_log::{timeways_rules::quest_log::Progress}::last_done_before]:
    Source: 'crates/rules/src/quest_log.rs', lines 187:4-195:5 -/
@[reducible]
def quest_log.Progress.last_done_before
  (self : quest_log.Progress) («end» : Std.Usize) :
  Result (Option Std.U64)
  := do
  quest_log.Progress.last_done_before_loop self «end» none 0#usize

/-- [timeways_rules::quest_log::{timeways_rules::quest_log::Progress}::opened_at]:
    Source: 'crates/rules/src/quest_log.rs', lines 175:4-183:5
    Visibility: public -/
def quest_log.Progress.opened_at
  (self : quest_log.Progress) (step : Std.Usize) :
  Result (Option Std.U64)
  := do
  let b ← quest_log.Progress.is_open self step
  if b
  then
    let i ← quest_log.Progress.stage_start self step
    let o ← quest_log.Progress.last_done_before self i
    match o with
    | none => ok self.accepted_at
    | some _ => ok o
  else ok none

/-- [timeways_rules::quest_log::{timeways_rules::quest_log::Progress}::ready_at]:
    Source: 'crates/rules/src/quest_log.rs', lines 199:4-211:5
    Visibility: public -/
def quest_log.Progress.ready_at
  (self : quest_log.Progress) (step : Std.Usize) :
  Result (Option Std.U64)
  := do
  let i := alloc.vec.Vec.len self.steps
  if step >= i
  then ok none
  else
    let g ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice
        quest_log.Goal) self.steps step
    match g with
    | quest_log.Goal.Wait days =>
      let o ← quest_log.Progress.opened_at self step
      match o with
      | none => ok none
      | some opened =>
        let i1 ← lift (core.convert.num.FromU64U8.from days)
        let i2 ← quest_log.DAY_SECONDS
        let i3 ← i1 * i2
        let i4 ← lift (core.num.U64.saturating_add opened i3)
        ok (some i4)
    | quest_log.Goal.Kill _ => ok none
    | quest_log.Goal.Other => ok none

/-- [timeways_rules::quest_log::{timeways_rules::quest_log::Progress}::finish_step]:
    Source: 'crates/rules/src/quest_log.rs', lines 215:4-228:5 -/
def quest_log.Progress.finish_step
  (self : quest_log.Progress) (step : Std.Usize) («at» : Std.U64) :
  Result quest_log.Progress
  := do
  let o ← quest_log.Progress.ready_at self step
  let early ←
    match o with
    | none => ok false
    | some ready => ok («at» < ready)
  let b ← quest_log.Progress.is_open self step
  if b
  then
    if early
    then ok self
    else
      let (_, index_mut_back) ←
        alloc.vec.Vec.index_mut (core.slice.index.SliceIndexUsizeSlice (Option
          Std.U64)) self.done_times step
      let v := index_mut_back (some «at»)
      let i ← quest_log.Progress.steps_done { self with done_times := v }
      let i1 := alloc.vec.Vec.len self.steps
      if i = i1
      then
        ok
          {
            self
              with
              status := quest_log.Status.Done,
              done_times := v,
              done_at := (some «at»)
          }
      else ok { self with done_times := v }
  else ok self

/-- [timeways_rules::quest_log::{timeways_rules::quest_log::Progress}::count_kill]:
    Source: 'crates/rules/src/quest_log.rs', lines 231:4-241:5 -/
def quest_log.Progress.count_kill
  (self : quest_log.Progress) (step : Std.Usize) :
  Result quest_log.Progress
  := do
  let i := alloc.vec.Vec.len self.steps
  if step >= i
  then ok self
  else
    let g ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice
        quest_log.Goal) self.steps step
    match g with
    | quest_log.Goal.Wait _ => ok self
    | quest_log.Goal.Kill count =>
      let b ← quest_log.Progress.is_open self step
      if b
      then
        let i1 ←
          alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice Std.U8)
            self.kills step
        if i1 < count
        then
          let (i2, index_mut_back) ←
            alloc.vec.Vec.index_mut (core.slice.index.SliceIndexUsizeSlice
              Std.U8) self.kills step
          let i3 ← i2 + 1#u8
          let v := index_mut_back i3
          ok { self with kills := v }
        else ok self
      else ok self
    | quest_log.Goal.Other => ok self

/-- [timeways_rules::quest_log::abandon]: loop 0:
    Source: 'crates/rules/src/quest_log.rs', lines 377:4-387:1 -/
@[rust_loop]
def quest_log.abandon_loop
  (quests : Slice quest_log.Quest) (number : Std.U64) (index : Std.Usize) :
  Result (Slice quest_log.Quest)
  := do
  let i := Slice.len quests
  if index < i
  then
    let (quest, index_mut_back) ← Slice.index_mut_usize quests index
    let b ←
      quest_log.Status.Insts.CoreCmpPartialEqStatus.eq quest.progress.status
        quest_log.Status.Offered
    let «open» ←
      if b
      then ok true
      else
        quest_log.Status.Insts.CoreCmpPartialEqStatus.eq quest.progress.status
          quest_log.Status.Accepted
    if quest.number = number
    then
      if «open»
      then
        ok (index_mut_back
          {
            quest
              with
              progress :=
                { quest.progress with status := quest_log.Status.Abandoned }
          })
      else
        let index1 ← index + 1#usize
        let s := index_mut_back quest
        quest_log.abandon_loop s number index1
    else
      let index1 ← index + 1#usize
      let s := index_mut_back quest
      quest_log.abandon_loop s number index1
  else ok quests
partial_fixpoint

/-- [timeways_rules::quest_log::abandon]:
    Source: 'crates/rules/src/quest_log.rs', lines 375:0-387:1 -/
@[reducible]
def quest_log.abandon
  (quests : Slice quest_log.Quest) (number : Std.U64) :
  Result (Slice quest_log.Quest)
  := do
  quest_log.abandon_loop quests number 0#usize

/-- [timeways_rules::quest_log::waiting_offer]: loop 0:
    Source: 'crates/rules/src/quest_log.rs', lines 363:4-369:5 -/
@[rust_loop]
def quest_log.waiting_offer_loop
  (quests : Slice quest_log.Quest) (number : Std.U64) (index : Std.Usize) :
  Result (Option Std.Usize)
  := do
  let i := Slice.len quests
  if index < i
  then
    let quest ← Slice.index_usize quests index
    if quest.number = number
    then
      let b ←
        quest_log.Status.Insts.CoreCmpPartialEqStatus.eq quest.progress.status
          quest_log.Status.Offered
      if b
      then ok (some index)
      else
        let index1 ← index + 1#usize
        quest_log.waiting_offer_loop quests number index1
    else
      let index1 ← index + 1#usize
      quest_log.waiting_offer_loop quests number index1
  else ok none
partial_fixpoint

/-- [timeways_rules::quest_log::waiting_offer]:
    Source: 'crates/rules/src/quest_log.rs', lines 361:0-371:1 -/
@[reducible]
def quest_log.waiting_offer
  (quests : Slice quest_log.Quest) (number : Std.U64) :
  Result (Option Std.Usize)
  := do
  quest_log.waiting_offer_loop quests number 0#usize

/-- [timeways_rules::quest_log::find]: loop 0:
    Source: 'crates/rules/src/quest_log.rs', lines 350:4-357:1 -/
@[rust_loop]
def quest_log.find_loop
  (quests : Slice quest_log.Quest) (number : Std.U64) (index : Std.Usize) :
  Result (Option Std.Usize)
  := do
  let i := Slice.len quests
  if index < i
  then
    let q ← Slice.index_usize quests index
    if q.number = number
    then ok (some index)
    else
      let index1 ← index + 1#usize
      quest_log.find_loop quests number index1
  else ok none
partial_fixpoint

/-- [timeways_rules::quest_log::find]:
    Source: 'crates/rules/src/quest_log.rs', lines 348:0-357:1 -/
@[reducible]
def quest_log.find
  (quests : Slice quest_log.Quest) (number : Std.U64) :
  Result (Option Std.Usize)
  := do
  quest_log.find_loop quests number 0#usize

/-- [timeways_rules::quest_log::decline_waiting_offers_of]: loop 0:
    Source: 'crates/rules/src/quest_log.rs', lines 337:4-343:5 -/
@[rust_loop]
def quest_log.decline_waiting_offers_of_loop
  (quests : Slice quest_log.Quest) (giver : String) (index : Std.Usize) :
  Result (Slice quest_log.Quest)
  := do
  let i := Slice.len quests
  if index < i
  then
    let (quest, index_mut_back) ← Slice.index_mut_usize quests index
    let b ←
      quest_log.Status.Insts.CoreCmpPartialEqStatus.eq quest.progress.status
        quest_log.Status.Offered
    let s ←
      if b
      then
        do
        let b1 ←
          alloc.string.String.Insts.CoreCmpPartialEqString.eq quest.giver giver
        if b1
        then ok quest_log.Status.Declined
        else ok quest.progress.status
      else ok quest.progress.status
    let index1 ← index + 1#usize
    let s1 :=
      index_mut_back
        { quest with progress := { quest.progress with status := s } }
    quest_log.decline_waiting_offers_of_loop s1 giver index1
  else ok quests
partial_fixpoint

/-- [timeways_rules::quest_log::decline_waiting_offers_of]:
    Source: 'crates/rules/src/quest_log.rs', lines 335:0-344:1 -/
@[reducible]
def quest_log.decline_waiting_offers_of
  (quests : Slice quest_log.Quest) (giver : String) :
  Result (Slice quest_log.Quest)
  := do
  quest_log.decline_waiting_offers_of_loop quests giver 0#usize

/-- [timeways_rules::quest_log::apply]:
    Source: 'crates/rules/src/quest_log.rs', lines 289:0-328:1 -/
def quest_log.apply
  (quests : alloc.vec.Vec quest_log.Quest) (change : quest_log.Change)
  (line : Std.Usize) :
  Result (alloc.vec.Vec quest_log.Quest)
  := do
  match change with
  | quest_log.Change.Offered number giver steps any_order =>
    let (s, deref_mut_back) ← lift (alloc.vec.Vec.deref_mut quests)
    let s1 ← quest_log.decline_waiting_offers_of s giver
    let quests1 := deref_mut_back s1
    let s2 ← alloc.string.String.Insts.CoreCloneClone.clone giver
    let s3 := alloc.vec.Vec.deref steps
    let p ← quest_log.Progress.offered s3 any_order
    alloc.vec.Vec.push quests1 ({ line, number, giver := s2, progress := p } :
      quest_log.Quest)
  | quest_log.Change.Accepted number «at» =>
    let s := alloc.vec.Vec.deref quests
    let o ← quest_log.waiting_offer s number
    match o with
    | none => ok quests
    | some index =>
      let (q, index_mut_back) ←
        alloc.vec.Vec.index_mut (core.slice.index.SliceIndexUsizeSlice
          quest_log.Quest) quests index
      let quests1 :=
        index_mut_back
          {
            q
              with
              progress :=
                { q.progress with status := quest_log.Status.Accepted }
          }
      let (q1, index_mut_back1) ←
        alloc.vec.Vec.index_mut (core.slice.index.SliceIndexUsizeSlice
          quest_log.Quest) quests1 index
      ok (index_mut_back1
        { q1 with progress := { q1.progress with accepted_at := (some «at») }
        })
  | quest_log.Change.Declined number =>
    let s := alloc.vec.Vec.deref quests
    let o ← quest_log.waiting_offer s number
    match o with
    | none => ok quests
    | some index =>
      let (q, index_mut_back) ←
        alloc.vec.Vec.index_mut (core.slice.index.SliceIndexUsizeSlice
          quest_log.Quest) quests index
      ok (index_mut_back
        {
          q
            with
            progress := { q.progress with status := quest_log.Status.Declined }
        })
  | quest_log.Change.StepDone number step «at» =>
    let s := alloc.vec.Vec.deref quests
    let o ← quest_log.find s number
    match o with
    | none => ok quests
    | some index =>
      let (q, index_mut_back) ←
        alloc.vec.Vec.index_mut (core.slice.index.SliceIndexUsizeSlice
          quest_log.Quest) quests index
      let p ← quest_log.Progress.finish_step q.progress step «at»
      ok (index_mut_back { q with progress := p })
  | quest_log.Change.Killed number step =>
    let s := alloc.vec.Vec.deref quests
    let o ← quest_log.find s number
    match o with
    | none => ok quests
    | some index =>
      let (q, index_mut_back) ←
        alloc.vec.Vec.index_mut (core.slice.index.SliceIndexUsizeSlice
          quest_log.Quest) quests index
      let p ← quest_log.Progress.count_kill q.progress step
      ok (index_mut_back { q with progress := p })
  | quest_log.Change.Abandoned number =>
    let (s, deref_mut_back) ← lift (alloc.vec.Vec.deref_mut quests)
    let s1 ← quest_log.abandon s number
    ok (deref_mut_back s1)

/-- [timeways_rules::quest_log::quest_log]: loop 0:
    Source: 'crates/rules/src/quest_log.rs', lines 282:4-285:5
    Visibility: public -/
@[rust_loop]
def quest_log.quest_log_loop
  (changes : Slice quest_log.Change) (quests : alloc.vec.Vec quest_log.Quest)
  (line : Std.Usize) :
  Result (alloc.vec.Vec quest_log.Quest)
  := do
  let i := Slice.len changes
  if line < i
  then
    let c ← Slice.index_usize changes line
    let quests1 ← quest_log.apply quests c line
    let line1 ← line + 1#usize
    quest_log.quest_log_loop changes quests1 line1
  else ok quests
partial_fixpoint

/-- [timeways_rules::quest_log::quest_log]:
    Source: 'crates/rules/src/quest_log.rs', lines 279:0-287:1
    Visibility: public -/
@[reducible]
def quest_log.quest_log
  (changes : Slice quest_log.Change) :
  Result (alloc.vec.Vec quest_log.Quest)
  := do
  quest_log.quest_log_loop changes (alloc.vec.Vec.new quest_log.Quest) 0#usize

/-- [timeways_rules::trust::MIN_TRUST]
    Source: 'crates/rules/src/trust.rs', lines 4:0-4:32
    Visibility: public -/
@[global_simps, irreducible] def trust.MIN_TRUST : Std.I64 := (-100)#i64

/-- [timeways_rules::trust::MAX_TRUST]
    Source: 'crates/rules/src/trust.rs', lines 5:0-5:31
    Visibility: public -/
@[global_simps, irreducible] def trust.MAX_TRUST : Std.I64 := 100#i64

/-- [timeways_rules::trust::next_trust]:
    Source: 'crates/rules/src/trust.rs', lines 10:0-14:1
    Visibility: public -/
def trust.next_trust
  (held : Option Std.I64) («by» : Std.I64) : Result Std.I64 := do
  let i ← lift (core.option.Option.unwrap_or held 0#i64)
  let i1 ← lift (core.num.I64.saturating_add i «by»)
  core.cmp.impls.OrdI64.clamp i1 trust.MIN_TRUST trust.MAX_TRUST

end timeways_rules
