-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [timeways_rules]: type definitions
module
public import Aeneas
@[expose] public section
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace timeways_rules

/-- [timeways_rules::aliases::PlayerId]
    Source: 'crates/rules/src/aliases.rs', lines 10:0-10:31
    Visibility: public -/
@[reducible]
def aliases.PlayerId := Std.Usize

/-- [timeways_rules::aliases::Alias]
    Source: 'crates/rules/src/aliases.rs', lines 14:0-19:1
    Visibility: public -/
structure aliases.Alias where
  key : String
  shown : String

/-- [timeways_rules::aliases::Piece]
    Source: 'crates/rules/src/aliases.rs', lines 23:0-32:1
    Visibility: public -/
@[discriminant isize]
inductive aliases.Piece where
| Text : String → aliases.Piece
| Word : String → String → aliases.Piece
| Player : aliases.PlayerId → aliases.Piece

/-- [timeways_rules::budget::Budget]
    Source: 'crates/rules/src/budget.rs', lines 9:0-11:1
    Visibility: public -/
structure budget.Budget where
  spoken : Array (Option Std.U64) 3#usize

/-- [timeways_rules::quest_log::Goal]
    Source: 'crates/rules/src/quest_log.rs', lines 14:0-18:1
    Visibility: public -/
@[discriminant isize]
inductive quest_log.Goal where
| Wait : Std.U8 → quest_log.Goal
| Kill : Std.U8 → quest_log.Goal
| Other : quest_log.Goal

/-- [timeways_rules::quest_log::Span]
    Source: 'crates/rules/src/quest_log.rs', lines 22:0-25:1
    Visibility: public -/
structure quest_log.Span where
  first : Std.Usize
  last : Std.Usize

/-- [timeways_rules::quest_log::Change]
    Source: 'crates/rules/src/quest_log.rs', lines 35:0-61:1
    Visibility: public -/
@[discriminant isize]
inductive quest_log.Change where
| Offered :
  Std.U64 →
  String →
  alloc.vec.Vec quest_log.Goal →
  Option quest_log.Span →
  quest_log.Change
| Accepted : Std.U64 → Std.U64 → quest_log.Change
| Declined : Std.U64 → quest_log.Change
| StepDone : Std.U64 → Std.Usize → Std.U64 → quest_log.Change
| Killed : Std.U64 → Std.Usize → quest_log.Change
| Abandoned : Std.U64 → quest_log.Change

/-- [timeways_rules::quest_log::Status]
    Source: 'crates/rules/src/quest_log.rs', lines 64:0-70:1
    Visibility: public -/
@[discriminant isize]
inductive quest_log.Status where
| Offered : quest_log.Status
| Accepted : quest_log.Status
| Declined : quest_log.Status
| Done : quest_log.Status
| Abandoned : quest_log.Status

/-- [timeways_rules::quest_log::Progress]
    Source: 'crates/rules/src/quest_log.rs', lines 82:0-93:1
    Visibility: public -/
structure quest_log.Progress where
  steps : alloc.vec.Vec quest_log.Goal
  any_order : Option quest_log.Span
  status : quest_log.Status
  accepted_at : Option Std.U64
  done_times : alloc.vec.Vec (Option Std.U64)
  kills : alloc.vec.Vec Std.U8
  done_at : Option Std.U64

/-- [timeways_rules::quest_log::Quest]
    Source: 'crates/rules/src/quest_log.rs', lines 73:0-79:1
    Visibility: public -/
structure quest_log.Quest where
  line : Std.Usize
  number : Std.U64
  giver : String
  progress : quest_log.Progress

end timeways_rules
